//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComplaintRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComplaintRegistration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.ComplaintRegistration", typeof(ComplaintRegistration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string FileUpload
        {
            get
            {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Category.
        /// </summary>
        public static string ComplaintCategory {
            get {
                return ResourceManager.GetString("ComplaintCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Code.
        /// </summary>
        public static string ComplaintCode {
            get {
                return ResourceManager.GetString("ComplaintCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Desc.
        /// </summary>
        public static string ComplaintDesc {
            get {
                return ResourceManager.GetString("ComplaintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Mode.
        /// </summary>
        public static string ComplaintMode {
            get {
                return ResourceManager.GetString("ComplaintMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Priority.
        /// </summary>
        public static string ComplaintPriority {
            get {
                return ResourceManager.GetString("ComplaintPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Received Date.
        /// </summary>
        public static string ComplaintReceivedDate {
            get {
                return ResourceManager.GetString("ComplaintReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Registration Date.
        /// </summary>
        public static string ComplaintRegistrationDate {
            get {
                return ResourceManager.GetString("ComplaintRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Severity.
        /// </summary>
        public static string ComplaintSeverity {
            get {
                return ResourceManager.GetString("ComplaintSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Tracking No.
        /// </summary>
        public static string ComplaintTrackingNo {
            get {
                return ResourceManager.GetString("ComplaintTrackingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Type.
        /// </summary>
        public static string ComplaintType {
            get {
                return ResourceManager.GetString("ComplaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Series Code.
        /// </summary>
        public static string CRSeriesCode {
            get {
                return ResourceManager.GetString("CRSeriesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Project Party ?.
        /// </summary>
        public static string IsProjectParty {
            get {
                return ResourceManager.GetString("IsProjectParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Belongs To.
        /// </summary>
        public static string Mat_MaterialBelongsTo {
            get {
                return ResourceManager.GetString("Mat_MaterialBelongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Mat_Name {
            get {
                return ResourceManager.GetString("Mat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Supplied From.
        /// </summary>
        public static string Mat_ProductSuppliedFrom {
            get {
                return ResourceManager.GetString("Mat_ProductSuppliedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Supply Detail.
        /// </summary>
        public static string MaterialSupplyDetail_PopUp {
            get {
                return ResourceManager.GetString("MaterialSupplyDetail_PopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature Of Complaint (Provide Technical Description of Complaint).
        /// </summary>
        public static string NatureOfComplaint {
            get {
                return ResourceManager.GetString("NatureOfComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation By HIL Official.
        /// </summary>
        public static string ObservationByHILOfficial {
            get {
                return ResourceManager.GetString("ObservationByHILOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        public static string RDFS_BatchNo {
            get {
                return ResourceManager.GetString("RDFS_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage Qty(Nos).
        /// </summary>
        public static string RDFS_BreakageQtyNos {
            get {
                return ResourceManager.GetString("RDFS_BreakageQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Type.
        /// </summary>
        public static string RDFS_DefectType {
            get {
                return ResourceManager.GetString("RDFS_DefectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string RDFS_InvoiceDate {
            get {
                return ResourceManager.GetString("RDFS_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string RDFS_InvoiceNo {
            get {
                return ResourceManager.GetString("RDFS_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type(Product Name).
        /// </summary>
        public static string RDFS_ItemTypeProductName {
            get {
                return ResourceManager.GetString("RDFS_ItemTypeProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Qty (Nos).
        /// </summary>
        public static string RDFS_ReceivedQtyNos {
            get {
                return ResourceManager.GetString("RDFS_ReceivedQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string RDFS_Remarks {
            get {
                return ResourceManager.GetString("RDFS_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(M).
        /// </summary>
        public static string RDFS_SizeM {
            get {
                return ResourceManager.GetString("RDFS_SizeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Defect.
        /// </summary>
        public static string RDFS_TypeofDefect {
            get {
                return ResourceManager.GetString("RDFS_TypeofDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptDetailsForSheeting.
        /// </summary>
        public static string ReceiptDetailsForSheeting_PopUp {
            get {
                return ResourceManager.GetString("ReceiptDetailsForSheeting_PopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrant Type.
        /// </summary>
        public static string RegistrantType {
            get {
                return ResourceManager.GetString("RegistrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Status.
        /// </summary>
        public static string RegistrationStatus {
            get {
                return ResourceManager.GetString("RegistrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Representative.
        /// </summary>
        public static string SalesRepresentative {
            get {
                return ResourceManager.GetString("SalesRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Representative Employee Code.
        /// </summary>
        public static string SalesRepresentativeEmployeeCode {
            get {
                return ResourceManager.GetString("SalesRepresentativeEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Representative Employee Name.
        /// </summary>
        public static string SalesRepresentativeEmployeeName {
            get {
                return ResourceManager.GetString("SalesRepresentativeEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        public static string SD_BatchNo {
            get {
                return ResourceManager.GetString("SD_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage Qty (Nos).
        /// </summary>
        public static string SD_BreakageQtyNos {
            get {
                return ResourceManager.GetString("SD_BreakageQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Type.
        /// </summary>
        public static string SD_DefectType {
            get {
                return ResourceManager.GetString("SD_DefectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string SD_InvoiceDate {
            get {
                return ResourceManager.GetString("SD_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string SD_InvoiceNo {
            get {
                return ResourceManager.GetString("SD_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string SD_ProductDetails {
            get {
                return ResourceManager.GetString("SD_ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string SD_Remarks {
            get {
                return ResourceManager.GetString("SD_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied Qty(Nos).
        /// </summary>
        public static string SD_SuppliedQtyNos {
            get {
                return ResourceManager.GetString("SD_SuppliedQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter.
        /// </summary>
        public static string SD_Transporter {
            get {
                return ResourceManager.GetString("SD_Transporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Address.
        /// </summary>
        public static string SiteAddress {
            get {
                return ResourceManager.GetString("SiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Stockiest/Direct Customer.
        /// </summary>
        public static string SubStockiestorDirectCustomer {
            get {
                return ResourceManager.GetString("SubStockiestorDirectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Detail.
        /// </summary>
        public static string SupplyDetail_PopUp {
            get {
                return ResourceManager.GetString("SupplyDetail_PopUp", resourceCulture);
            }
        }
    }
}
