//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Compensation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Compensation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.Compensation", typeof(Compensation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Special Remarks.
        /// </summary>
        public static string AnySpecialRemarks {
            get {
                return ResourceManager.GetString("AnySpecialRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage(%).
        /// </summary>
        public static string BID_BreakagePer {
            get {
                return ResourceManager.GetString("BID_BreakagePer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage Qty(M).
        /// </summary>
        public static string BID_BreakageQtyM {
            get {
                return ResourceManager.GetString("BID_BreakageQtyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage Qty(Nos).
        /// </summary>
        public static string BID_BreakageQtyNos {
            get {
                return ResourceManager.GetString("BID_BreakageQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage Qty(Ton).
        /// </summary>
        public static string BID_BreakageQtyTon {
            get {
                return ResourceManager.GetString("BID_BreakageQtyTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Type.
        /// </summary>
        public static string BID_DefectType {
            get {
                return ResourceManager.GetString("BID_DefectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Wt(Tons).
        /// </summary>
        public static string BID_GrossWtTons {
            get {
                return ResourceManager.GetString("BID_GrossWtTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(Product Name).
        /// </summary>
        public static string BID_ItemProductName {
            get {
                return ResourceManager.GetString("BID_ItemProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type(Product Name).
        /// </summary>
        public static string BID_ItemTypeProductName {
            get {
                return ResourceManager.GetString("BID_ItemTypeProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string BID_Remarks {
            get {
                return ResourceManager.GetString("BID_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(M).
        /// </summary>
        public static string BID_SizeM {
            get {
                return ResourceManager.GetString("BID_SizeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied Qty(M).
        /// </summary>
        public static string BID_SuppliedQtyM {
            get {
                return ResourceManager.GetString("BID_SuppliedQtyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied Qty(Nos).
        /// </summary>
        public static string BID_SuppliedQtyNos {
            get {
                return ResourceManager.GetString("BID_SuppliedQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied Qty(Ton).
        /// </summary>
        public static string BID_SuppliedQtyTon {
            get {
                return ResourceManager.GetString("BID_SuppliedQtyTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuppliedQtytons.
        /// </summary>
        public static string BID_SuppliedQtyTons {
            get {
                return ResourceManager.GetString("BID_SuppliedQtyTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage &amp; Investigation Details.
        /// </summary>
        public static string BreakageInvestigationDetailsPopUp {
            get {
                return ResourceManager.GetString("BreakageInvestigationDetailsPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Breakage Qty (No&apos;s).
        /// </summary>
        public static string CompBreakageOtherActualBreakageQtyNos {
            get {
                return ResourceManager.GetString("CompBreakageOtherActualBreakageQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Breakage (%).
        /// </summary>
        public static string CompBreakageOtherAllowedBreakagePercentage {
            get {
                return ResourceManager.GetString("CompBreakageOtherAllowedBreakagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string CompBreakageOtherRemarks {
            get {
                return ResourceManager.GetString("CompBreakageOtherRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string CompBreakageOtherSNo {
            get {
                return ResourceManager.GetString("CompBreakageOtherSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied Qty(No&apos;s).
        /// </summary>
        public static string CompBreakageOtherSuppliedQty {
            get {
                return ResourceManager.GetString("CompBreakageOtherSuppliedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Breakage Qty (No&apos;s).
        /// </summary>
        public static string CompBreakageOtherTotalBreakageQty {
            get {
                return ResourceManager.GetString("CompBreakageOtherTotalBreakageQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Breakage (%).
        /// </summary>
        public static string CompBreakageOtherTotalBreakageQtyPercentage {
            get {
                return ResourceManager.GetString("CompBreakageOtherTotalBreakageQtyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter.
        /// </summary>
        public static string CompBreakageOtherTransporter {
            get {
                return ResourceManager.GetString("CompBreakageOtherTransporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Breakage Qty(No&apos;s).
        /// </summary>
        public static string CompBreakLinesOtherActualBreakageQtyNos {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherActualBreakageQtyNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Breakage(%).
        /// </summary>
        public static string CompBreakLinesOtherAllowedBreakagePercentage {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherAllowedBreakagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Breakage Lines.
        /// </summary>
        public static string CompBreakLinesOtherHeading {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string CompBreakLinesOtherRemarks {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied Qty(No&apos;s).
        /// </summary>
        public static string CompBreakLinesOtherSuppliedQtyNo {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherSuppliedQtyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Breakage Qty(No&apos;s).
        /// </summary>
        public static string CompBreakLinesOtherTotalBreakageQtyNo {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherTotalBreakageQtyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Breakage(%).
        /// </summary>
        public static string CompBreakLinesOtherTotalBreakageQtyPercentage {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherTotalBreakageQtyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter.
        /// </summary>
        public static string CompBreakLinesOtherTransporter {
            get {
                return ResourceManager.GetString("CompBreakLinesOtherTransporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Credited.
        /// </summary>
        public static string CompensationAmountCredited {
            get {
                return ResourceManager.GetString("CompensationAmountCredited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation Date.
        /// </summary>
        public static string CompensationDate {
            get {
                return ResourceManager.GetString("CompensationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation Id.
        /// </summary>
        public static string CompensationId {
            get {
                return ResourceManager.GetString("CompensationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation in.
        /// </summary>
        public static string CompensationinMetricCubic {
            get {
                return ResourceManager.GetString("CompensationinMetricCubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation In Nos.
        /// </summary>
        public static string CompensationInNos {
            get {
                return ResourceManager.GetString("CompensationInNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation In Nos(Words).
        /// </summary>
        public static string CompensationInNosWords {
            get {
                return ResourceManager.GetString("CompensationInNosWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation In Running Meters.
        /// </summary>
        public static string CompensationInRunningMeters {
            get {
                return ResourceManager.GetString("CompensationInRunningMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation In Running Meter (Words).
        /// </summary>
        public static string CompensationInRunningMeterWords {
            get {
                return ResourceManager.GetString("CompensationInRunningMeterWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation In Tons.
        /// </summary>
        public static string CompensationInTons {
            get {
                return ResourceManager.GetString("CompensationInTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Credit Note.
        /// </summary>
        public static string CompensationIssueCreditNote {
            get {
                return ResourceManager.GetString("CompensationIssueCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation Mode.
        /// </summary>
        public static string CompensationMode {
            get {
                return ResourceManager.GetString("CompensationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Weight.
        /// </summary>
        public static string CompensationSizeLinePopUpGrossWeight {
            get {
                return ResourceManager.GetString("CompensationSizeLinePopUpGrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Compensation Recommendation Lines.
        /// </summary>
        public static string CompensationSizeLinePopUpHeading {
            get {
                return ResourceManager.GetString("CompensationSizeLinePopUpHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos.
        /// </summary>
        public static string CompensationSizeLinePopUpNos {
            get {
                return ResourceManager.GetString("CompensationSizeLinePopUpNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Size.
        /// </summary>
        public static string CompensationSizeLinePopUpRecommendedSize {
            get {
                return ResourceManager.GetString("CompensationSizeLinePopUpRecommendedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons.
        /// </summary>
        public static string CompensationSizeLinePopUpTons {
            get {
                return ResourceManager.GetString("CompensationSizeLinePopUpTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Weight.
        /// </summary>
        public static string CompensationSizeLinesGrossWeight {
            get {
                return ResourceManager.GetString("CompensationSizeLinesGrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos.
        /// </summary>
        public static string CompensationSizeLinesNos {
            get {
                return ResourceManager.GetString("CompensationSizeLinesNos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Size.
        /// </summary>
        public static string CompensationSizeLinesRecommendSize {
            get {
                return ResourceManager.GetString("CompensationSizeLinesRecommendSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string CompensationSizeLinesSNo {
            get {
                return ResourceManager.GetString("CompensationSizeLinesSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons.
        /// </summary>
        public static string CompensationSizeLinesTons {
            get {
                return ResourceManager.GetString("CompensationSizeLinesTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation Status.
        /// </summary>
        public static string CompensationStatus {
            get {
                return ResourceManager.GetString("CompensationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Attendent Date.
        /// </summary>
        public static string ComplaintAttendentDate {
            get {
                return ResourceManager.GetString("ComplaintAttendentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Description.
        /// </summary>
        public static string ComplaintDescription {
            get {
                return ResourceManager.GetString("ComplaintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint No.
        /// </summary>
        public static string ComplaintNo {
            get {
                return ResourceManager.GetString("ComplaintNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Received Date.
        /// </summary>
        public static string ComplaintReceivedDate {
            get {
                return ResourceManager.GetString("ComplaintReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Registered Date.
        /// </summary>
        public static string ComplaintRegisteredDate {
            get {
                return ResourceManager.GetString("ComplaintRegisteredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Tracking No.
        /// </summary>
        public static string ComplaintTrackingNo {
            get {
                return ResourceManager.GetString("ComplaintTrackingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMP Series Code.
        /// </summary>
        public static string COMPSeriesCode {
            get {
                return ResourceManager.GetString("COMPSeriesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Supply From.
        /// </summary>
        public static string DateSupplyFrom {
            get {
                return ResourceManager.GetString("DateSupplyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Supply To.
        /// </summary>
        public static string DateSupplyTo {
            get {
                return ResourceManager.GetString("DateSupplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Sign.
        /// </summary>
        public static string DigitalSign {
            get {
                return ResourceManager.GetString("DigitalSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Date.
        /// </summary>
        public static string InvestigationDate {
            get {
                return ResourceManager.GetString("InvestigationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Done By.
        /// </summary>
        public static string InvestigationDoneBy {
            get {
                return ResourceManager.GetString("InvestigationDoneBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Num.
        /// </summary>
        public static string InvestigationNum {
            get {
                return ResourceManager.GetString("InvestigationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Remarks.
        /// </summary>
        public static string InvestigationRemarks {
            get {
                return ResourceManager.GetString("InvestigationRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Based.
        /// </summary>
        public static string InvoiceBased {
            get {
                return ResourceManager.GetString("InvoiceBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Details.
        /// </summary>
        public static string InvoiceDetails {
            get {
                return ResourceManager.GetString("InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Project Party ?.
        /// </summary>
        public static string IsProjectParty {
            get {
                return ResourceManager.GetString("IsProjectParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Supply Detail.
        /// </summary>
        public static string MaterialSupplyDetailPopUp {
            get {
                return ResourceManager.GetString("MaterialSupplyDetailPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage Qty.
        /// </summary>
        public static string MSD_BreakageQty {
            get {
                return ResourceManager.GetString("MSD_BreakageQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Belongs To.
        /// </summary>
        public static string MSD_MaterialBelongsTo {
            get {
                return ResourceManager.GetString("MSD_MaterialBelongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MSD_Name {
            get {
                return ResourceManager.GetString("MSD_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Loss Qty.
        /// </summary>
        public static string MSD_NetLossQty {
            get {
                return ResourceManager.GetString("MSD_NetLossQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Supplied From.
        /// </summary>
        public static string MSD_ProductSuppliedFrom {
            get {
                return ResourceManager.GetString("MSD_ProductSuppliedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Qty.
        /// </summary>
        public static string MSD_SupplyQty {
            get {
                return ResourceManager.GetString("MSD_SupplyQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string MSD_UOM {
            get {
                return ResourceManager.GetString("MSD_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Loss(Mtrs).
        /// </summary>
        public static string NetLossMtrs {
            get {
                return ResourceManager.GetString("NetLossMtrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Loss(Tons).
        /// </summary>
        public static string NetLossTons {
            get {
                return ResourceManager.GetString("NetLossTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of 3.6.
        /// </summary>
        public static string Noof36 {
            get {
                return ResourceManager.GetString("Noof36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Size(RMTS).
        /// </summary>
        public static string OtherSizeRMTS {
            get {
                return ResourceManager.GetString("OtherSizeRMTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Based.
        /// </summary>
        public static string PeriodBased {
            get {
                return ResourceManager.GetString("PeriodBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Visit Date.
        /// </summary>
        public static string PreviousVisitDate {
            get {
                return ResourceManager.GetString("PreviousVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Representative Employee Code.
        /// </summary>
        public static string SalesRepresentativeEmployeeCode {
            get {
                return ResourceManager.GetString("SalesRepresentativeEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Representative Employee Name.
        /// </summary>
        public static string SalesRepresentativeEmployeeName {
            get {
                return ResourceManager.GetString("SalesRepresentativeEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Address.
        /// </summary>
        public static string SiteAddress {
            get {
                return ResourceManager.GetString("SiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Visit Date.
        /// </summary>
        public static string SiteVisitDate {
            get {
                return ResourceManager.GetString("SiteVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Recommendation (RMTS Of 3.6 M).
        /// </summary>
        public static string SizeRecommendationRMTSOf36M {
            get {
                return ResourceManager.GetString("SizeRecommendationRMTSOf36M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Stockiest/Direct Customer.
        /// </summary>
        public static string SubStockiestDirectCustomer {
            get {
                return ResourceManager.GetString("SubStockiestDirectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Breakage Qty(Mtrs).
        /// </summary>
        public static string TotalBreakageQtyMtrs {
            get {
                return ResourceManager.GetString("TotalBreakageQtyMtrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Breakage Qty(Tons).
        /// </summary>
        public static string TotalBreakageQtyTons {
            get {
                return ResourceManager.GetString("TotalBreakageQtyTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Recovery(Mtrs).
        /// </summary>
        public static string TotalRecoveryMtrs {
            get {
                return ResourceManager.GetString("TotalRecoveryMtrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Recovery(Tons).
        /// </summary>
        public static string TotalRecoveryTons {
            get {
                return ResourceManager.GetString("TotalRecoveryTons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Supply Qty(Mtrs).
        /// </summary>
        public static string TotalSupplyQtyMtrs {
            get {
                return ResourceManager.GetString("TotalSupplyQtyMtrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Supply Qty(Tons).
        /// </summary>
        public static string TotalSupplyQtyTons {
            get {
                return ResourceManager.GetString("TotalSupplyQtyTons", resourceCulture);
            }
        }
    }
}
