//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorrectiveMeasures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorrectiveMeasures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.CorrectiveMeasures", typeof(CorrectiveMeasures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Date.
        /// </summary>
        public static string ApprovedDate {
            get {
                return ResourceManager.GetString("ApprovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        public static string BatchNo {
            get {
                return ResourceManager.GetString("BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string ChosenPermanentActionName {
            get {
                return ResourceManager.GetString("ChosenPermanentActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string ChosenPermanentActualDate {
            get {
                return ResourceManager.GetString("ChosenPermanentActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Permanent Corrective Action(s).
        /// </summary>
        public static string ChosenPermanentCorrectiveAction {
            get {
                return ResourceManager.GetString("ChosenPermanentCorrectiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ChosenPermanentDescription {
            get {
                return ResourceManager.GetString("ChosenPermanentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Corrective Chosen Permanent Lines.
        /// </summary>
        public static string ChosenPermanentLinesHeading {
            get {
                return ResourceManager.GetString("ChosenPermanentLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string ChosenPermanentModel_ActionName {
            get {
                return ResourceManager.GetString("ChosenPermanentModel_ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string ChosenPermanentModel_ActualDate {
            get {
                return ResourceManager.GetString("ChosenPermanentModel_ActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ChosenPermanentModel_Description {
            get {
                return ResourceManager.GetString("ChosenPermanentModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string ChosenPermanentModel_RelatedTo {
            get {
                return ResourceManager.GetString("ChosenPermanentModel_RelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string ChosenPermanentModel_Remarks {
            get {
                return ResourceManager.GetString("ChosenPermanentModel_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string ChosenPermanentModel_TargetDate {
            get {
                return ResourceManager.GetString("ChosenPermanentModel_TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string ChosenPermanentRelatedTo {
            get {
                return ResourceManager.GetString("ChosenPermanentRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string ChosenPermanentRemarks {
            get {
                return ResourceManager.GetString("ChosenPermanentRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string ChosenPermanentSNo {
            get {
                return ResourceManager.GetString("ChosenPermanentSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string ChosenPermanentTargetDate {
            get {
                return ResourceManager.GetString("ChosenPermanentTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM Doc Status.
        /// </summary>
        public static string CMDocStatus {
            get {
                return ResourceManager.GetString("CMDocStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM Series Code.
        /// </summary>
        public static string CMSeriesCode {
            get {
                return ResourceManager.GetString("CMSeriesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Note Details.
        /// </summary>
        public static string CommunicationNoteDetails {
            get {
                return ResourceManager.GetString("CommunicationNoteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Note ID.
        /// </summary>
        public static string CommunicationNoteID {
            get {
                return ResourceManager.GetString("CommunicationNoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Category.
        /// </summary>
        public static string ComplaintCategory {
            get {
                return ResourceManager.GetString("ComplaintCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Desc.
        /// </summary>
        public static string ComplaintDesc {
            get {
                return ResourceManager.GetString("ComplaintDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Registered Date.
        /// </summary>
        public static string ComplaintRegisteredDate {
            get {
                return ResourceManager.GetString("ComplaintRegisteredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Tracking No.
        /// </summary>
        public static string ComplaintTrackingNo {
            get {
                return ResourceManager.GetString("ComplaintTrackingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Type.
        /// </summary>
        public static string ComplaintType {
            get {
                return ResourceManager.GetString("ComplaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclusion.
        /// </summary>
        public static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Corrective Emergency Lines.
        /// </summary>
        public static string CorrectiveEmergencyLinesHeading {
            get {
                return ResourceManager.GetString("CorrectiveEmergencyLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string CorrectiveIntermLineActionName {
            get {
                return ResourceManager.GetString("CorrectiveIntermLineActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string CorrectiveIntermLineActualDate {
            get {
                return ResourceManager.GetString("CorrectiveIntermLineActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CorrectiveIntermLineDescription {
            get {
                return ResourceManager.GetString("CorrectiveIntermLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string CorrectiveIntermLineRelatedTo {
            get {
                return ResourceManager.GetString("CorrectiveIntermLineRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string CorrectiveIntermLineRemarks {
            get {
                return ResourceManager.GetString("CorrectiveIntermLineRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Corrective Interm Lines.
        /// </summary>
        public static string CorrectiveIntermLines {
            get {
                return ResourceManager.GetString("CorrectiveIntermLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string CorrectiveIntermLineTargetDate {
            get {
                return ResourceManager.GetString("CorrectiveIntermLineTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Measure Date.
        /// </summary>
        public static string CorrectiveMeasureDate {
            get {
                return ResourceManager.GetString("CorrectiveMeasureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Measure Id.
        /// </summary>
        public static string CorrectiveMeasureId {
            get {
                return ResourceManager.GetString("CorrectiveMeasureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Measure Remarks.
        /// </summary>
        public static string CorrectiveMeasureRemarks {
            get {
                return ResourceManager.GetString("CorrectiveMeasureRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrective Measure Status.
        /// </summary>
        public static string CorrectiveMeasureStatus {
            get {
                return ResourceManager.GetString("CorrectiveMeasureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Corrective Observation Lines.
        /// </summary>
        public static string CorrectiveObservationLinesHeading {
            get {
                return ResourceManager.GetString("CorrectiveObservationLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Name.
        /// </summary>
        public static string CorrectiveObservationLinesObservationName {
            get {
                return ResourceManager.GetString("CorrectiveObservationLinesObservationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Corrective Preventive Lines.
        /// </summary>
        public static string CorrectivePreventiveLinesHeading {
            get {
                return ResourceManager.GetString("CorrectivePreventiveLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string CorrectivePreventiveModel_ActionName {
            get {
                return ResourceManager.GetString("CorrectivePreventiveModel_ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string CorrectivePreventiveModel_ActualDate {
            get {
                return ResourceManager.GetString("CorrectivePreventiveModel_ActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CorrectivePreventiveModel_Description {
            get {
                return ResourceManager.GetString("CorrectivePreventiveModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CorrectivePreventiveModel_Name {
            get {
                return ResourceManager.GetString("CorrectivePreventiveModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string CorrectivePreventiveModel_RelatedTo {
            get {
                return ResourceManager.GetString("CorrectivePreventiveModel_RelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string CorrectivePreventiveModel_Remarks {
            get {
                return ResourceManager.GetString("CorrectivePreventiveModel_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string CorrectivePreventiveModel_TargetDate {
            get {
                return ResourceManager.GetString("CorrectivePreventiveModel_TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Corrective Team Lines.
        /// </summary>
        public static string CorrectiveTeamLinesHeading {
            get {
                return ResourceManager.GetString("CorrectiveTeamLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CorrectiveTeamLinesName {
            get {
                return ResourceManager.GetString("CorrectiveTeamLinesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string CorrectiveTeamLinesRemarks {
            get {
                return ResourceManager.GetString("CorrectiveTeamLinesRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string CorrectiveTeamLinesRole {
            get {
                return ResourceManager.GetString("CorrectiveTeamLinesRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        public static string CorrectiveTeamLinesTeamMembers {
            get {
                return ResourceManager.GetString("CorrectiveTeamLinesTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string Defect {
            get {
                return ResourceManager.GetString("Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string EmergencyModelActionName {
            get {
                return ResourceManager.GetString("EmergencyModelActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string EmergencyModelActualDate {
            get {
                return ResourceManager.GetString("EmergencyModelActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EmergencyModelDescription {
            get {
                return ResourceManager.GetString("EmergencyModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string EmergencyModelRemarks {
            get {
                return ResourceManager.GetString("EmergencyModelRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string EmergencyModelTargetDate {
            get {
                return ResourceManager.GetString("EmergencyModelTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string EmergencyResponseActionName {
            get {
                return ResourceManager.GetString("EmergencyResponseActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Response Actions.
        /// </summary>
        public static string EmergencyResponseActions {
            get {
                return ResourceManager.GetString("EmergencyResponseActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string EmergencyResponseActualDate {
            get {
                return ResourceManager.GetString("EmergencyResponseActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EmergencyResponseDescription {
            get {
                return ResourceManager.GetString("EmergencyResponseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string EmergencyResponseRemarks {
            get {
                return ResourceManager.GetString("EmergencyResponseRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNo.
        /// </summary>
        public static string EmergencyResponseSNo {
            get {
                return ResourceManager.GetString("EmergencyResponseSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string EmergencyResponseTargetDate {
            get {
                return ResourceManager.GetString("EmergencyResponseTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented Corrective Action Details.
        /// </summary>
        public static string ImplementedCorrectiveActionDetails {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveActionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string ImplementedCorrectiveActualDate {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Action Name.
        /// </summary>
        public static string ImplementedCorrectiveChosenActionName {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveChosenActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ImplementedCorrectiveDescription {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string ImplementedCorrectiveRelatedTo {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string ImplementedCorrectiveRemarks {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string ImplementedCorrectiveSNo {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string ImplementedCorrectiveTargetDate {
            get {
                return ResourceManager.GetString("ImplementedCorrectiveTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Implement Lines.
        /// </summary>
        public static string ImplementLinesHeading {
            get {
                return ResourceManager.GetString("ImplementLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string ImplementModel_ActualDate {
            get {
                return ResourceManager.GetString("ImplementModel_ActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Action Name.
        /// </summary>
        public static string ImplementModel_ChosenActionName {
            get {
                return ResourceManager.GetString("ImplementModel_ChosenActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ImplementModel_Description {
            get {
                return ResourceManager.GetString("ImplementModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string ImplementModel_RelatedTo {
            get {
                return ResourceManager.GetString("ImplementModel_RelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string ImplementModel_Remarks {
            get {
                return ResourceManager.GetString("ImplementModel_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string ImplementModel_TargetDate {
            get {
                return ResourceManager.GetString("ImplementModel_TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string InterimContainmentActionName {
            get {
                return ResourceManager.GetString("InterimContainmentActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interim Containment Actions.
        /// </summary>
        public static string InterimContainmentActions {
            get {
                return ResourceManager.GetString("InterimContainmentActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string InterimContainmentActualDate {
            get {
                return ResourceManager.GetString("InterimContainmentActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InterimContainmentDescription {
            get {
                return ResourceManager.GetString("InterimContainmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string InterimContainmentRelatedTo {
            get {
                return ResourceManager.GetString("InterimContainmentRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string InterimContainmentRemarks {
            get {
                return ResourceManager.GetString("InterimContainmentRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string InterimContainmentSNo {
            get {
                return ResourceManager.GetString("InterimContainmentSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string InterimContainmentTargetDate {
            get {
                return ResourceManager.GetString("InterimContainmentTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Date.
        /// </summary>
        public static string InvestigationDate {
            get {
                return ResourceManager.GetString("InvestigationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Done By.
        /// </summary>
        public static string InvestigationDoneBy {
            get {
                return ResourceManager.GetString("InvestigationDoneBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigation Num.
        /// </summary>
        public static string InvestigationNum {
            get {
                return ResourceManager.GetString("InvestigationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Communication Note.
        /// </summary>
        public static string IssueCommunicationNote {
            get {
                return ResourceManager.GetString("IssueCommunicationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Defective Sheets.
        /// </summary>
        public static string NoofDefectiveSheets {
            get {
                return ResourceManager.GetString("NoofDefectiveSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Issued Date.
        /// </summary>
        public static string NoticeIssuedDate {
            get {
                return ResourceManager.GetString("NoticeIssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Remarks/Additional information.
        /// </summary>
        public static string NoticeRemarksAdditionalinformation {
            get {
                return ResourceManager.GetString("NoticeRemarksAdditionalinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Type.
        /// </summary>
        public static string NoticeType {
            get {
                return ResourceManager.GetString("NoticeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string ObservationByInvestigationSNo {
            get {
                return ResourceManager.GetString("ObservationByInvestigationSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Name.
        /// </summary>
        public static string ObservationName {
            get {
                return ResourceManager.GetString("ObservationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations By Investigator.
        /// </summary>
        public static string ObservationsByInvestigator {
            get {
                return ResourceManager.GetString("ObservationsByInvestigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant.
        /// </summary>
        public static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string PreventiveActionName {
            get {
                return ResourceManager.GetString("PreventiveActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventive Actions Details.
        /// </summary>
        public static string PreventiveActionsDetails {
            get {
                return ResourceManager.GetString("PreventiveActionsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string PreventiveActualDate {
            get {
                return ResourceManager.GetString("PreventiveActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PreventiveDescription {
            get {
                return ResourceManager.GetString("PreventiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PreventiveName {
            get {
                return ResourceManager.GetString("PreventiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related To.
        /// </summary>
        public static string PreventiveRelatedTo {
            get {
                return ResourceManager.GetString("PreventiveRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string PreventiveRemarks {
            get {
                return ResourceManager.GetString("PreventiveRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string PreventiveSNo {
            get {
                return ResourceManager.GetString("PreventiveSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string PreventiveTargetDate {
            get {
                return ResourceManager.GetString("PreventiveTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Preventive Verification Lines.
        /// </summary>
        public static string PreventiveVerificationLines {
            get {
                return ResourceManager.GetString("PreventiveVerificationLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string PreventiveVerificationModel_ActualDate {
            get {
                return ResourceManager.GetString("PreventiveVerificationModel_ActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Percent.
        /// </summary>
        public static string PreventiveVerificationModel_EffectivePercent {
            get {
                return ResourceManager.GetString("PreventiveVerificationModel_EffectivePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventive Action Name.
        /// </summary>
        public static string PreventiveVerificationModel_PreventiveActionName {
            get {
                return ResourceManager.GetString("PreventiveVerificationModel_PreventiveActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventive Line Id.
        /// </summary>
        public static string PreventiveVerificationModel_PreventiveLineId {
            get {
                return ResourceManager.GetString("PreventiveVerificationModel_PreventiveLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string PreventiveVerificationModel_Remarks {
            get {
                return ResourceManager.GetString("PreventiveVerificationModel_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string PreventiveVerificationModel_TargetDate {
            get {
                return ResourceManager.GetString("PreventiveVerificationModel_TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string PreventiveVerificationModel_Validation {
            get {
                return ResourceManager.GetString("PreventiveVerificationModel_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Description.
        /// </summary>
        public static string ProblemDescription {
            get {
                return ResourceManager.GetString("ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Impact.
        /// </summary>
        public static string ProblemImpact {
            get {
                return ResourceManager.GetString("ProblemImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Cause(s) and Escape Point.
        /// </summary>
        public static string RootCauseEscapePoint {
            get {
                return ResourceManager.GetString("RootCauseEscapePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RootCauseEscapePointCauseName {
            get {
                return ResourceManager.GetString("RootCauseEscapePointCauseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RootCauseEscapePointDescription {
            get {
                return ResourceManager.GetString("RootCauseEscapePointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Findings.
        /// </summary>
        public static string RootCauseEscapePointFindings {
            get {
                return ResourceManager.GetString("RootCauseEscapePointFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedTo.
        /// </summary>
        public static string RootCauseEscapePointRelatedTo {
            get {
                return ResourceManager.GetString("RootCauseEscapePointRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string RootCauseEscapePointRemarks {
            get {
                return ResourceManager.GetString("RootCauseEscapePointRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string RootCauseEscapePointSNo {
            get {
                return ResourceManager.GetString("RootCauseEscapePointSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause Name.
        /// </summary>
        public static string RootCauseLinesCauseName {
            get {
                return ResourceManager.GetString("RootCauseLinesCauseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RootCauseLinesDescription {
            get {
                return ResourceManager.GetString("RootCauseLinesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Findings.
        /// </summary>
        public static string RootCauseLinesFindings {
            get {
                return ResourceManager.GetString("RootCauseLinesFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Root Cause Lines.
        /// </summary>
        public static string RootCauseLinesHeading {
            get {
                return ResourceManager.GetString("RootCauseLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedTo.
        /// </summary>
        public static string RootCauseLinesRelatedTo {
            get {
                return ResourceManager.GetString("RootCauseLinesRelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string RootCauseLinesRemarks {
            get {
                return ResourceManager.GetString("RootCauseLinesRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms.
        /// </summary>
        public static string Symptoms {
            get {
                return ResourceManager.GetString("Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Involved.
        /// </summary>
        public static string TeamInvolved {
            get {
                return ResourceManager.GetString("TeamInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TeamInvolvedName {
            get {
                return ResourceManager.GetString("TeamInvolvedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string TeamInvolvedRemarks {
            get {
                return ResourceManager.GetString("TeamInvolvedRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string TeamInvolvedRole {
            get {
                return ResourceManager.GetString("TeamInvolvedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string TeamInvolvedSNo {
            get {
                return ResourceManager.GetString("TeamInvolvedSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        public static string TeamInvolvedTeamMembers {
            get {
                return ResourceManager.GetString("TeamInvolvedTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Update Verification Lines.
        /// </summary>
        public static string VerificationLinesHeading {
            get {
                return ResourceManager.GetString("VerificationLinesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string VerificationModel_ActualDate {
            get {
                return ResourceManager.GetString("VerificationModel_ActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Percent.
        /// </summary>
        public static string VerificationModel_EffectivePercent {
            get {
                return ResourceManager.GetString("VerificationModel_EffectivePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented Action Name.
        /// </summary>
        public static string VerificationModel_ImplementedActionName {
            get {
                return ResourceManager.GetString("VerificationModel_ImplementedActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplementedLine Id.
        /// </summary>
        public static string VerificationModel_ImplementedLineId {
            get {
                return ResourceManager.GetString("VerificationModel_ImplementedLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string VerificationModel_Remarks {
            get {
                return ResourceManager.GetString("VerificationModel_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string VerificationModel_TargetDate {
            get {
                return ResourceManager.GetString("VerificationModel_TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string VerificationModel_Validation {
            get {
                return ResourceManager.GetString("VerificationModel_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification of Corrective Actions.
        /// </summary>
        public static string VerificationofCorrectiveActions {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string VerificationofCorrectiveActualDate {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Percent.
        /// </summary>
        public static string VerificationofCorrectiveEffectivePercent {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveEffectivePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string VerificationofCorrectiveImplementActionName {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveImplementActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImplementLine Id.
        /// </summary>
        public static string VerificationofCorrectiveImplementLineId {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveImplementLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string VerificationofCorrectiveRemarks {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string VerificationofCorrectiveSNo {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string VerificationofCorrectiveTargetDate {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string VerificationofCorrectiveValidation {
            get {
                return ResourceManager.GetString("VerificationofCorrectiveValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification of Preventive Actions.
        /// </summary>
        public static string VerificationofPreventiveActions {
            get {
                return ResourceManager.GetString("VerificationofPreventiveActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Date.
        /// </summary>
        public static string VerificationofPreventiveActualDate {
            get {
                return ResourceManager.GetString("VerificationofPreventiveActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Percent.
        /// </summary>
        public static string VerificationofPreventiveEffectivePercent {
            get {
                return ResourceManager.GetString("VerificationofPreventiveEffectivePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string VerificationofPreventivePreventiveActionName {
            get {
                return ResourceManager.GetString("VerificationofPreventivePreventiveActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreventiveLine Id.
        /// </summary>
        public static string VerificationofPreventivePreventiveLineId {
            get {
                return ResourceManager.GetString("VerificationofPreventivePreventiveLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string VerificationofPreventiveRemarks {
            get {
                return ResourceManager.GetString("VerificationofPreventiveRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No.
        /// </summary>
        public static string VerificationofPreventiveSNo {
            get {
                return ResourceManager.GetString("VerificationofPreventiveSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string VerificationofPreventiveTargetDate {
            get {
                return ResourceManager.GetString("VerificationofPreventiveTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string VerificationofPreventiveValidation {
            get {
                return ResourceManager.GetString("VerificationofPreventiveValidation", resourceCulture);
            }
        }
    }
}
