//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateTargetFC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateTargetFC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.CreateTargetFC", typeof(CreateTargetFC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Sales Huddle.
        /// </summary>
        public static string DailySalesHuddle {
            get {
                return ResourceManager.GetString("DailySalesHuddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSO Emp ID.
        /// </summary>
        public static string FSOEmpID {
            get {
                return ResourceManager.GetString("FSOEmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSO Name.
        /// </summary>
        public static string FSOName {
            get {
                return ResourceManager.GetString("FSOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSO Target.
        /// </summary>
        public static string FSOTarget {
            get {
                return ResourceManager.GetString("FSOTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey Plan.
        /// </summary>
        public static string JourneyPlan {
            get {
                return ResourceManager.GetString("JourneyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Stockist Volume.
        /// </summary>
        public static string KeyStockistVolume {
            get {
                return ResourceManager.GetString("KeyStockistVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Sales Review.
        /// </summary>
        public static string MonthlySalesReview {
            get {
                return ResourceManager.GetString("MonthlySalesReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month &amp; Year.
        /// </summary>
        public static string MonthYear {
            get {
                return ResourceManager.GetString("MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stockist Conversion Plan.
        /// </summary>
        public static string NewStockistConversionPlan {
            get {
                return ResourceManager.GetString("NewStockistConversionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #New Stockists Appointed.
        /// </summary>
        public static string NewStockistsAppointed {
            get {
                return ResourceManager.GetString("NewStockistsAppointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stockist Volume.
        /// </summary>
        public static string NewStockistVolume {
            get {
                return ResourceManager.GetString("NewStockistVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sub-Stockist Conversion Plan.
        /// </summary>
        public static string NewSubStockistConversionPlan {
            get {
                return ResourceManager.GetString("NewSubStockistConversionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sub-stockist conversion plan.
        /// </summary>
        public static string NewSubStockistConversionPlanxcvxv {
            get {
                return ResourceManager.GetString("NewSubStockistConversionPlanxcvxv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #New Sub-Stockists Appointed.
        /// </summary>
        public static string NewSubStockistsAppointed {
            get {
                return ResourceManager.GetString("NewSubStockistsAppointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sub-Stockist Volume.
        /// </summary>
        public static string NewSubStockistVolume {
            get {
                return ResourceManager.GetString("NewSubStockistVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Sales Volume (Target).
        /// </summary>
        public static string OverallSalesVolumeTarget {
            get {
                return ResourceManager.GetString("OverallSalesVolumeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Adherence to PJP.
        /// </summary>
        public static string PercentAdherencetoPJP {
            get {
                return ResourceManager.GetString("PercentAdherencetoPJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Stockist Billed.
        /// </summary>
        public static string PercentStockistBilled {
            get {
                return ResourceManager.GetString("PercentStockistBilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Stockist Inventory Tracked by FSO.
        /// </summary>
        public static string PercentStockistInventoryTrackedbyFSO {
            get {
                return ResourceManager.GetString("PercentStockistInventoryTrackedbyFSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Stockists Tracking Inventory.
        /// </summary>
        public static string PercentStockistsTrackingInventory {
            get {
                return ResourceManager.GetString("PercentStockistsTrackingInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Visits Planned vs Actual.
        /// </summary>
        public static string PercentVisitsPlannedvsActual {
            get {
                return ResourceManager.GetString("PercentVisitsPlannedvsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        public static string SalesEmployeeCode {
            get {
                return ResourceManager.GetString("SalesEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string SalesEmployeeName {
            get {
                return ResourceManager.GetString("SalesEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Role/ Designation.
        /// </summary>
        public static string SalesEmployeeRoleDesignation {
            get {
                return ResourceManager.GetString("SalesEmployeeRoleDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Head Emp Code.
        /// </summary>
        public static string StateHeadEmpCode {
            get {
                return ResourceManager.GetString("StateHeadEmpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Head Name.
        /// </summary>
        public static string StateHeadName {
            get {
                return ResourceManager.GetString("StateHeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Target.
        /// </summary>
        public static string StateTarget {
            get {
                return ResourceManager.GetString("StateTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Stockist Issues Open for &gt; 30 Days.
        /// </summary>
        public static string StockistIssuesOpenfor30Days {
            get {
                return ResourceManager.GetString("StockistIssuesOpenfor30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Manager.
        /// </summary>
        public static string TerritoryManager {
            get {
                return ResourceManager.GetString("TerritoryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM Emp ID.
        /// </summary>
        public static string TMEmpID {
            get {
                return ResourceManager.GetString("TMEmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM Target.
        /// </summary>
        public static string TMTarget {
            get {
                return ResourceManager.GetString("TMTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Sales Review.
        /// </summary>
        public static string WeeklySalesReview {
            get {
                return ResourceManager.GetString("WeeklySalesReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string ZonalSalesHead {
            get {
                return ResourceManager.GetString("ZonalSalesHead", resourceCulture);
            }
        }
    }
}
