//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentSeries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentSeries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.DocumentSeries", typeof(DocumentSeries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Series Code.
        /// </summary>
        public static string DocumentSeriesCode {
            get {
                return ResourceManager.GetString("DocumentSeriesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNo.
        /// </summary>
        public static string DocumentSeriesSno {
            get {
                return ResourceManager.GetString("DocumentSeriesSno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Period.
        /// </summary>
        public static string FinancialPeriod {
            get {
                return ResourceManager.GetString("FinancialPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Num.
        /// </summary>
        public static string FirstNum {
            get {
                return ResourceManager.GetString("FirstNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Num.
        /// </summary>
        public static string LastNum {
            get {
                return ResourceManager.GetString("LastNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Num.
        /// </summary>
        public static string NextNum {
            get {
                return ResourceManager.GetString("NextNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Prefix.
        /// </summary>
        public static string SeriesPrefix {
            get {
                return ResourceManager.GetString("SeriesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Suffix.
        /// </summary>
        public static string SeriesSuffix {
            get {
                return ResourceManager.GetString("SeriesSuffix", resourceCulture);
            }
        }
    }
}
