//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JourneyPlanList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JourneyPlanList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.JourneyPlanList", typeof(JourneyPlanList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string From_Date {
            get {
                return ResourceManager.GetString("From_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Employee.
        /// </summary>
        public static string SalesEmployee {
            get {
                return ResourceManager.GetString("SalesEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stockist ID.
        /// </summary>
        public static string StockistID {
            get {
                return ResourceManager.GetString("StockistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string StockistName {
            get {
                return ResourceManager.GetString("StockistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Visits.
        /// </summary>
        public static string TblActuaVisits {
            get {
                return ResourceManager.GetString("TblActuaVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Customer.
        /// </summary>
        public static string TblCountofStockist {
            get {
                return ResourceManager.GetString("TblCountofStockist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of Sub-Customer.
        /// </summary>
        public static string TblCountofSubStockist {
            get {
                return ResourceManager.GetString("TblCountofSubStockist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journey Plan Name.
        /// </summary>
        public static string TblJourneyPlanName {
            get {
                return ResourceManager.GetString("TblJourneyPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Name.
        /// </summary>
        public static string TblMonthName {
            get {
                return ResourceManager.GetString("TblMonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Start Date.
        /// </summary>
        public static string TblMonthStartDate {
            get {
                return ResourceManager.GetString("TblMonthStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Days in Month.
        /// </summary>
        public static string TblNoofDaysinMonth {
            get {
                return ResourceManager.GetString("TblNoofDaysinMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Alias.
        /// </summary>
        public static string TblOwnerAlias {
            get {
                return ResourceManager.GetString("TblOwnerAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string TblRating {
            get {
                return ResourceManager.GetString("TblRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales District.
        /// </summary>
        public static string TblSalesDistrict {
            get {
                return ResourceManager.GetString("TblSalesDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Employee Name.
        /// </summary>
        public static string TblSalesEmployeeName {
            get {
                return ResourceManager.GetString("TblSalesEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Region.
        /// </summary>
        public static string TblSalesRegion {
            get {
                return ResourceManager.GetString("TblSalesRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TblStatus {
            get {
                return ResourceManager.GetString("TblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Visits.
        /// </summary>
        public static string TblTotalVisits {
            get {
                return ResourceManager.GetString("TblTotalVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View or Edit Journey Plan.
        /// </summary>
        public static string TblVieworEditJourneyPlan {
            get {
                return ResourceManager.GetString("TblVieworEditJourneyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory/Area.
        /// </summary>
        public static string Territory_Area {
            get {
                return ResourceManager.GetString("Territory_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string To_Date {
            get {
                return ResourceManager.GetString("To_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
