//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JourneyPlanDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JourneyPlanDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.JourneyPlanDetails", typeof(JourneyPlanDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Volume MTD (MT).
        /// </summary>
        public static string TblActualVolumeMTD {
            get {
                return ResourceManager.GetString("TblActualVolumeMTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Date for Next Order.
        /// </summary>
        public static string TblExpectedDateforNextOrder {
            get {
                return ResourceManager.GetString("TblExpectedDateforNextOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order Date.
        /// </summary>
        public static string TblLastOrderDate {
            get {
                return ResourceManager.GetString("TblLastOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quarter Monthly Average (MT).
        /// </summary>
        public static string TblLastQuarterMonthlyAverageMT {
            get {
                return ResourceManager.GetString("TblLastQuarterMonthlyAverageMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year Same Month (MT).
        /// </summary>
        public static string TblLastYearSameMonthMT {
            get {
                return ResourceManager.GetString("TblLastYearSameMonthMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of days in Month.
        /// </summary>
        public static string TblNoofdaysofStockAvg {
            get {
                return ResourceManager.GetString("TblNoofdaysofStockAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales District.
        /// </summary>
        public static string TblSalesDistrict {
            get {
                return ResourceManager.GetString("TblSalesDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Region.
        /// </summary>
        public static string TblSalesRegion {
            get {
                return ResourceManager.GetString("TblSalesRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string TblStockist {
            get {
                return ResourceManager.GetString("TblStockist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string TblSubStockist {
            get {
                return ResourceManager.GetString("TblSubStockist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Plan for Month (MT).
        /// </summary>
        public static string TblVolumePlanforMonthMT {
            get {
                return ResourceManager.GetString("TblVolumePlanforMonthMT", resourceCulture);
            }
        }
    }
}
