//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MarketMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.MarketMap", typeof(MarketMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By Alias.
        /// </summary>
        public static string CreatedByAlias {
            get {
                return ResourceManager.GetString("CreatedByAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of days of Stock (Avg).
        /// </summary>
        public static string NoofdaysofStockAvg {
            get {
                return ResourceManager.GetString("NoofdaysofStockAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string SalesEmployee {
            get {
                return ResourceManager.GetString("SalesEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string StockistID {
            get {
                return ResourceManager.GetString("StockistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string StockistName {
            get {
                return ResourceManager.GetString("StockistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor.
        /// </summary>
        public static string TblCompetitor {
            get {
                return ResourceManager.GetString("TblCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stock (MT).
        /// </summary>
        public static string TblCurrentStockMT {
            get {
                return ResourceManager.GetString("TblCurrentStockMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record ID.
        /// </summary>
        public static string TblRecordID {
            get {
                return ResourceManager.GetString("TblRecordID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales District.
        /// </summary>
        public static string TblSalesDistrict {
            get {
                return ResourceManager.GetString("TblSalesDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Region.
        /// </summary>
        public static string TblSalesRegion {
            get {
                return ResourceManager.GetString("TblSalesRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string TblStockistID {
            get {
                return ResourceManager.GetString("TblStockistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string TblStockistName {
            get {
                return ResourceManager.GetString("TblStockistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Capacity (MT).
        /// </summary>
        public static string TblStorageCapacityMT {
            get {
                return ResourceManager.GetString("TblStorageCapacityMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory/Area.
        /// </summary>
        public static string TerritoryArea {
            get {
                return ResourceManager.GetString("TerritoryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Counter Sale.
        /// </summary>
        public static string TotalCounterSale {
            get {
                return ResourceManager.GetString("TotalCounterSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
