//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.Content.Resource_Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SchemesList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchemesList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIMS.Content.Resource_Files.SchemesList", typeof(SchemesList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        public static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string TblBonus {
            get {
                return ResourceManager.GetString("TblBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TblCategory {
            get {
                return ResourceManager.GetString("TblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligibility.
        /// </summary>
        public static string TblEligibility {
            get {
                return ResourceManager.GetString("TblEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string TblEndDate {
            get {
                return ResourceManager.GetString("TblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TblLocation {
            get {
                return ResourceManager.GetString("TblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string TblProduct {
            get {
                return ResourceManager.GetString("TblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme Desc.
        /// </summary>
        public static string TblSchemeDesc {
            get {
                return ResourceManager.GetString("TblSchemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme ID.
        /// </summary>
        public static string TblSchemeID {
            get {
                return ResourceManager.GetString("TblSchemeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme Name.
        /// </summary>
        public static string TblSchemeName {
            get {
                return ResourceManager.GetString("TblSchemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date .
        /// </summary>
        public static string TblStartDate {
            get {
                return ResourceManager.GetString("TblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string TblState {
            get {
                return ResourceManager.GetString("TblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TblStatus {
            get {
                return ResourceManager.GetString("TblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        public static string TblTerritory {
            get {
                return ResourceManager.GetString("TblTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string TblZone {
            get {
                return ResourceManager.GetString("TblZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory/Area.
        /// </summary>
        public static string TerritoryArea {
            get {
                return ResourceManager.GetString("TerritoryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
