//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACKUP_06292017_sap_outstanding_details
    {
        public System.DateTime aging_date { get; set; }
        public string customer_code { get; set; }
        public string business_area { get; set; }
        public Nullable<decimal> days_0015 { get; set; }
        public Nullable<decimal> days_1630 { get; set; }
        public Nullable<decimal> days_3145 { get; set; }
        public Nullable<decimal> days_4660 { get; set; }
        public Nullable<decimal> days_6175 { get; set; }
        public Nullable<decimal> days_7690 { get; set; }
        public Nullable<decimal> days_91120 { get; set; }
        public Nullable<decimal> days_121150 { get; set; }
        public Nullable<decimal> days_151179 { get; set; }
        public Nullable<decimal> days_180 { get; set; }
        public Nullable<decimal> days_ab180 { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
