//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bak_sappendingcforms
    {
        public int ID { get; set; }
        public long STOCKIST_ID { get; set; }
        public string STOCKIST_NAME { get; set; }
        public string ZONE { get; set; }
        public string STATE { get; set; }
        public string TERRITORY { get; set; }
        public string LOCATION { get; set; }
        public string BUSINESS { get; set; }
        public long BILL_DOC { get; set; }
        public string FINANCIAL_YEAR { get; set; }
        public System.DateTime BILL_DATE { get; set; }
        public string MONTH { get; set; }
        public string MONTH1 { get; set; }
        public decimal TAXABLE_TURNOVER { get; set; }
        public string MATERIAL_SUPPLIED_FROM { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
