//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bck_sap_invoice_item_data_010916_1900
    {
        public int LINE_ID { get; set; }
        public string DOC_NO { get; set; }
        public string ITEM { get; set; }
        public string PLANT_CODE { get; set; }
        public string SALES_GROUP_CODE { get; set; }
        public string MATERIAL_NO { get; set; }
        public Nullable<decimal> BILL_QTY { get; set; }
        public string UNITS { get; set; }
        public Nullable<decimal> NET_WT { get; set; }
        public Nullable<decimal> GROSS_WT { get; set; }
        public string RATE_PER_UNIT { get; set; }
        public string SALES_ZONE_CODE { get; set; }
        public string SALES_STATE_CODE { get; set; }
        public string TERRITORY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<decimal> TBASAMT { get; set; }
        public Nullable<decimal> URATE { get; set; }
        public Nullable<decimal> ITEM_AMOUNT { get; set; }
    }
}
