//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_compensation
    {
        public cms_compensation()
        {
            this.cms_compensation_recommendation_lines = new HashSet<cms_compensation_recommendation_lines>();
        }
    
        public int ID { get; set; }
        public System.DateTime COMPLAINT_RECEIVED_DATE { get; set; }
        public System.DateTime COMPLAINT_ATTENDENT_DATE { get; set; }
        public System.DateTime COMPLAINT_REGISTERED_DATE { get; set; }
        public string COMPLAINT_DESC { get; set; }
        public string PRODUCT_CATEGORY_CODE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> SITE_VISIT_DATE { get; set; }
        public Nullable<System.DateTime> VISITED_DATE { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string INVESTIGATOR_TYPE_CODE { get; set; }
        public string Customer_type_Code { get; set; }
        public string Project_Party { get; set; }
        public string Cusomer_Location { get; set; }
        public string Customer_Address { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string ZONE_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string PLANT_CODE { get; set; }
        public string DEPO_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public string Observations_by_Investigator { get; set; }
        public string BREAKAGE_COMPENSATION_TYPE_CODE { get; set; }
        public Nullable<double> COMPENSATION_IN_METERS_SHEET { get; set; }
        public string COMPENSATION_IN__METER_WORDS_SHEET { get; set; }
        public Nullable<double> COMPENSATION_IN_TONS { get; set; }
        public Nullable<double> RECOMMENDED_SIZE { get; set; }
        public Nullable<double> OTHER_SIZE { get; set; }
        public string ISSUE_CREDIT_NOTE { get; set; }
        public string COMMENTS_APPROVALS_SALES { get; set; }
        public string SPECIAL_REMARKS { get; set; }
        public Nullable<int> COMPENSATION_IN_NO { get; set; }
        public string COMPENSATION_IN_WORD { get; set; }
        public Nullable<double> COMPENSATION_IN_CUBIC_METER { get; set; }
        public string COMPENSATION_IN_METER_OTHER { get; set; }
        public string COMPENSATION_IN_METER_WORDS_OTHER { get; set; }
        public Nullable<double> AMOUNT_CREDITED { get; set; }
        public string Supplied_From_Name { get; set; }
        public Nullable<System.DateTime> Date_Supply_From { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> DRAFT_NUM { get; set; }
        public Nullable<int> DOC_NUM { get; set; }
        public string DOC_SERIES_CODE { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string DOC_STATUS { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public Nullable<int> INVESTIGATION_ID { get; set; }
        public string INVESTIGATION_DOC_SERIES { get; set; }
        public Nullable<int> INVESTIGATION_DOC_NUM { get; set; }
        public string INVESTIGATION_DONE_BY { get; set; }
        public Nullable<System.DateTime> INVESTIGATION_DATE { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string SUPPLIED_FROM { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<System.DateTime> DATE_SUPPLY_TO { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string Customer_Code { get; set; }
        public Nullable<int> COMPLAINT_ID { get; set; }
        public string COMPLAINT_DOC_SERIES { get; set; }
        public Nullable<int> COMPLAINT_DOC_NUM { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public string CITY_CODE { get; set; }
        public Nullable<double> SUPPLY_QTY_TONS { get; set; }
        public Nullable<double> SUPPLY_QTY_MTRS { get; set; }
        public Nullable<double> BREAKAGE_QTY_TONS { get; set; }
        public Nullable<double> BREAKAGE_QTY_MTRS { get; set; }
        public Nullable<double> NET_LOSS_QTY_TONS { get; set; }
        public Nullable<double> NET_LOSS_QTY_MTRS { get; set; }
        public string SPECIAL_REMARKS_OTHERS { get; set; }
        public string COMMENTS_APPROVALS_SALES_OTHERS { get; set; }
        public string MATERIAL_BELONGS_TO_CODE { get; set; }
        public string STOCKIEST_CODE { get; set; }
        public string SUB_STOCKIEST { get; set; }
        public string MULTIPLE_INVOICE { get; set; }
        public string ALL_INVOICE_NO { get; set; }
        public string ALL_INVOICE_DATE { get; set; }
        public string END_CUSTOMER_DETAILS { get; set; }
        public string COMPENSATION_MODE_CODE { get; set; }
        public Nullable<double> RECOVERY_QTY_MTRS { get; set; }
        public Nullable<double> RECOVERY_QTY_TONS { get; set; }
        public string INVOICE_BASED { get; set; }
        public string PERIOD_BASED { get; set; }
        public Nullable<System.DateTime> PREVIOUS_VISIT_DATE { get; set; }
        public string DIGITAL_SIGN { get; set; }
        public string CANCEL_REMARKS { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string CANCEL_BY { get; set; }
        public string Invoice_number { get; set; }
        public string Material_Number { get; set; }
        public string SALES_REPRESENTATIVE_CODE { get; set; }
        public string APPROVED_BY { get; set; }
        public string party_type { get; set; }
        public string SubStockiest_Code { get; set; }
        public string SubStockiest_Name { get; set; }
        public string SubStockiest_Address { get; set; }
        public string SubStockiest_Number { get; set; }
        public Nullable<int> COMPLAINT_TYPE { get; set; }
        public string CREATED_IN { get; set; }
    
        public virtual ICollection<cms_compensation_recommendation_lines> cms_compensation_recommendation_lines { get; set; }
    }
}
