//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_RC_Supply_Details_STO
    {
        public int ID { get; set; }
        public int COMPLAINT_TRACKING_NO { get; set; }
        public string INVOICE_NO { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<int> SUPPLIED_NO { get; set; }
        public Nullable<int> DEFECTED_NO { get; set; }
        public string TRANSPORTER { get; set; }
        public string DEFECT_TYPE_CODE { get; set; }
        public string REMARKS { get; set; }
    
        public virtual cms_register_complaints_sto cms_register_complaints_sto { get; set; }
    }
}
