//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_investigation_breakage_inspection_sheet
    {
        public int LINE_ID { get; set; }
        public int ID { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<double> SIZE { get; set; }
        public string BATCH_NO { get; set; }
        public string DEFECT_TYPE_CODE { get; set; }
        public string RECOVERYPRODUCT_CODE { get; set; }
        public string RECOVERY { get; set; }
        public Nullable<double> GrossWeight { get; set; }
    }
}
