//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_reports
    {
        public cms_reports()
        {
            this.cms_report_config = new HashSet<cms_report_config>();
        }
    
        public int ID { get; set; }
        public string REPORT_NAME { get; set; }
        public string REPORT_PATH { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public string EXTENSION { get; set; }
    
        public virtual ICollection<cms_report_config> cms_report_config { get; set; }
    }
}
