//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_print_upload
    {
        public int ID { get; set; }
        public string LAYOUT_NAME { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public byte[] REPORT_DESIGN { get; set; }
        public string REPORT_LOCATION { get; set; }
        public string DEFAULT_REPORT { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual cms_documentmaster cms_documentmaster { get; set; }
    }
}
