//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_compensation_supply_details_BU3
    {
        public int LINE_ID { get; set; }
        public int ID { get; set; }
        public string ProdCode { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string BatchNo { get; set; }
        public Nullable<double> SupplyQty { get; set; }
        public Nullable<double> DefectQty { get; set; }
        public Nullable<double> ActualDefectQty { get; set; }
        public string Transporter { get; set; }
        public string Remarks { get; set; }
        public string DefectType { get; set; }
    }
}
