//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_dimensions_for_ac_sheet
    {
        public int ID { get; set; }
        public string PRODUCT_TYPE_NAME { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> WEIGHT_OF_1_UOM { get; set; }
    }
}
