//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_dimentions_for_division
    {
        public string DIVISION_CODE { get; set; }
        public string SIZE { get; set; }
        public string COLOR { get; set; }
        public string THICKNESS { get; set; }
        public Nullable<decimal> SIZE_IN_INCHES { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> QUANTITY_IN_SHEET { get; set; }
        public Nullable<decimal> QUANTITY_IN_RUNNING_METER { get; set; }
        public Nullable<decimal> QUANTITY_IN_MT { get; set; }
    }
}
