//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_register_complaints
    {
        public cms_register_complaints()
        {
            this.cms_register_complaints_emp_lines = new HashSet<cms_register_complaints_emp_lines>();
            this.cms_register_complaints_msf = new HashSet<cms_register_complaints_msf>();
            this.cms_register_complaints_receipts_lines = new HashSet<cms_register_complaints_receipts_lines>();
        }
    
        public int ID { get; set; }
        public string COMPLAINT_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string PROJECT_PARTY { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string LOCATION_CODE { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string PRODUCT_CATEGORY_CODE { get; set; }
        public string ZONE_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public Nullable<System.DateTime> COMPLAINT_RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> REPORTED_DATE { get; set; }
        public string REGISTRANT_TYPE_CODE { get; set; }
        public string COMPLAINT_PRIORITY_CODE { get; set; }
        public string COMPLAINT_SEVERITY_CODE { get; set; }
        public string COMPLAINT_MODE_CODE { get; set; }
        public string COMPLAINT_TYPE_CODE { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string REMARKS { get; set; }
        public string SIZE { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> DRAFT_NUM { get; set; }
        public Nullable<int> DOC_NUM { get; set; }
        public string DOC_SERIES_CODE { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string DOC_STATUS { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string DOC_REFERENCE_NO { get; set; }
        public string COMPLAINT_CATEGORY_CODE { get; set; }
        public string COMPLAINT_DESC { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string CUSTOMER_TYPE_CODE { get; set; }
        public string NATURE_OF_COMPLAINT { get; set; }
        public string OBSERVATIONSBY_OFFICIAL { get; set; }
        public Nullable<System.DateTime> DATE_OF_VISIT { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public string CITY_CODE { get; set; }
        public string MATERIAL_BELONGS_TO_CODE { get; set; }
        public string PRODUCT_SUPPLIED_FROM_CODE { get; set; }
        public Nullable<int> STOCKIEST_ID { get; set; }
        public string SUB_STOCKIEST { get; set; }
        public string END_CUSTOMER_DETAILS { get; set; }
        public string CANCEL_REMARKS { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string CANCEL_BY { get; set; }
        public Nullable<System.DateTime> COMPLAINT_REGISTRATION_DATE { get; set; }
        public string COMPLAINT_TRACKING_NO { get; set; }
        public string SITE_ADDRESS { get; set; }
        public string SALES_REPRESENTATIVE_CODE { get; set; }
        public string APPROVED_BY { get; set; }
        public string ATTACHMENTS { get; set; }
        public string party_type { get; set; }
        public string SubStockiest_Code { get; set; }
        public string SubStockiest_Name { get; set; }
        public string SubStockiest_Address { get; set; }
        public string SubStockiest_Number { get; set; }
        public Nullable<int> COMPLAINT_TYPE { get; set; }
        public Nullable<bool> set_visible_draft_status { get; set; }
        public string CREATED_IN { get; set; }
    
        public virtual ICollection<cms_register_complaints_emp_lines> cms_register_complaints_emp_lines { get; set; }
        public virtual ICollection<cms_register_complaints_msf> cms_register_complaints_msf { get; set; }
        public virtual ICollection<cms_register_complaints_receipts_lines> cms_register_complaints_receipts_lines { get; set; }
    }
}
