//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_users_auth
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int OBJECT_ID { get; set; }
        public string DOC_ACCESS { get; set; }
        public string DOC_ADD { get; set; }
        public string DOC_VIEW { get; set; }
        public string DOC_UPDATE { get; set; }
        public string DOC_DELETE { get; set; }
        public string APPLICATION_CODE { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> SITEDETAIL_ID { get; set; }
        public string EXPORT_TO_EXCEL { get; set; }
        public string EXPORT_TO_PDF { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual cms_users cms_users { get; set; }
        public virtual cms_users cms_users1 { get; set; }
    }
}
