//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_TYPE_OF_COMPLAINTS
    {
        public int id { get; set; }
        public string COMPLAINT_TYPE { get; set; }
        public Nullable<int> status { get; set; }
    }
}
