//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_RC_Material_Supply_Details_STO
    {
        public int ID { get; set; }
        public int COMPLAINT_TRACKING_NO { get; set; }
        public string PLANT_CODE { get; set; }
        public string SUPPLIER_TYPE_CODE { get; set; }
        public string SUPPLIER_CODE { get; set; }
    
        public virtual cms_register_complaints_sto cms_register_complaints_sto { get; set; }
    }
}
