//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_organization_level_11052018
    {
        public int ORG_LEVEL_ID { get; set; }
        public string ORG_LEVEL_NAME { get; set; }
        public int PARENT_ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
    }
}
