//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_users
    {
        public cms_users()
        {
            this.cms_usermaster_producttype_lines = new HashSet<cms_usermaster_producttype_lines>();
            this.cms_users_roles = new HashSet<cms_users_roles>();
            this.cms_users_auth = new HashSet<cms_users_auth>();
            this.cms_users_auth1 = new HashSet<cms_users_auth>();
            this.cms_users_roles1 = new HashSet<cms_users_roles>();
        }
    
        public int ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string BRANCH { get; set; }
        public string FAX { get; set; }
        public string MOBILE_NO { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public string COMPANY_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public string PLANT_CODE { get; set; }
        public string DEPO_CODE { get; set; }
        public string LOCATION_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string ZONE_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public string USER_ROLE_CODE { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public string CITY_CODE { get; set; }
        public string DOCUMENT_DISPLAY { get; set; }
        public string digital_signature { get; set; }
    
        public virtual ICollection<cms_usermaster_producttype_lines> cms_usermaster_producttype_lines { get; set; }
        public virtual ICollection<cms_users_roles> cms_users_roles { get; set; }
        public virtual ICollection<cms_users_auth> cms_users_auth { get; set; }
        public virtual ICollection<cms_users_auth> cms_users_auth1 { get; set; }
        public virtual ICollection<cms_users_roles> cms_users_roles1 { get; set; }
    }
}
