//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_employee_role_configuration
    {
        public int ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string USER_ROLE_CODE { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public string ZONE { get; set; }
        public string STATE { get; set; }
        public string DEPO_COORDINATOR { get; set; }
        public string PLANT_COORDINATOR { get; set; }
        public string REPORT_TO_WHOOM { get; set; }
        public Nullable<int> ORG_LEVEL_ID { get; set; }
        public string TERRITORY { get; set; }
    }
}
