//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_zone_state_mapping_backup_08012019
    {
        public int ID { get; set; }
        public string ZONE_CODE { get; set; }
        public string STATE_CODE { get; set; }
    }
}
