//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_USER_ROLE_PRODUCT_TYPE_MAPPING
    {
        public int id { get; set; }
        public string REPORT_NAME { get; set; }
        public string USER_ROLE_CODE { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
