//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_workflow_approverlist
    {
        public int LINE_ID { get; set; }
        public Nullable<int> WF_ID { get; set; }
        public Nullable<int> LINE_NUM { get; set; }
        public Nullable<int> STAGE { get; set; }
        public string APPROVER { get; set; }
        public string APPROVED { get; set; }
        public string MANDATORY { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string APPROVER_NAME { get; set; }
    }
}
