//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_compensation_msf
    {
        public int LINE_ID { get; set; }
        public int ID { get; set; }
        public string SUPPLY_TYPE_CODE { get; set; }
        public string SUPPLY_CODE { get; set; }
        public string OTHERS { get; set; }
        public string PLANT_CODE { get; set; }
        public string CBPLANT { get; set; }
        public string CBDEPO { get; set; }
        public string CBSTOCK { get; set; }
        public Nullable<double> NET_LOSS { get; set; }
        public string UOM { get; set; }
        public Nullable<double> supply_qty { get; set; }
        public Nullable<double> breakage_qty { get; set; }
        public string SUPPLY_NAME { get; set; }
        public string SUPPLY_TYPE_NAME { get; set; }
        public string PLANT_NAME { get; set; }
    }
}
