//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_compensation_recommendation_lines
    {
        public int LINE_ID { get; set; }
        public int ID { get; set; }
        public Nullable<int> LINE_NUM { get; set; }
        public string RECOMMENDED_SIZE { get; set; }
        public Nullable<int> NOS { get; set; }
        public Nullable<double> GROSS_WEIGHT { get; set; }
        public Nullable<double> TONS { get; set; }
        public string PLANT_CODE { get; set; }
    
        public virtual cms_compensation cms_compensation { get; set; }
    }
}
