//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_compensation_breakage_sheeting_lines
    {
        public int LINE_ID { get; set; }
        public Nullable<double> SIZE_MM { get; set; }
        public Nullable<double> SIZE_TONS { get; set; }
        public string INVOICE_NO { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<double> SUPPLIED_QTY { get; set; }
        public Nullable<double> BREAKAGE_QTY { get; set; }
        public Nullable<double> NET_LOSS_QUANTITY { get; set; }
        public Nullable<double> BREAKAGE_PERSENT { get; set; }
        public string REMARKS { get; set; }
        public int ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<int> SUPPLIED_QTY_NO { get; set; }
        public Nullable<int> BREAKAGE_QTY_NO { get; set; }
        public Nullable<double> NET_LOSS { get; set; }
        public string batch_no { get; set; }
        public string DEFECT_TYPE_CODE { get; set; }
        public Nullable<double> SUPPLIED_QTY_TON { get; set; }
        public Nullable<double> BREAKAGE_QTY_TON { get; set; }
    }
}
