//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_documentmaster
    {
        public cms_documentmaster()
        {
            this.cms_documentseries = new HashSet<cms_documentseries>();
            this.cms_documentseries1 = new HashSet<cms_documentseries>();
            this.cms_print_upload = new HashSet<cms_print_upload>();
        }
    
        public int ID { get; set; }
        public string DOCUMENT_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string DOCUMENT_NAME { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODULE_NAME { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public string Pojo_Name { get; set; }
    
        public virtual ICollection<cms_documentseries> cms_documentseries { get; set; }
        public virtual ICollection<cms_documentseries> cms_documentseries1 { get; set; }
        public virtual ICollection<cms_print_upload> cms_print_upload { get; set; }
    }
}
