//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_COMPLAINT_STATUS_ICC
    {
        public int ID { get; set; }
        public string COMPLAINT_TRACKING_NO { get; set; }
        public string COMPLAINT_CODE { get; set; }
        public string COMPLAINT_STATUS { get; set; }
        public Nullable<System.DateTime> COMPLAINT_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> INVESTIGATED_DATE { get; set; }
    }
}
