//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_complain_assign
    {
        public int ID { get; set; }
        public Nullable<int> COMPLAIN_DOCNO { get; set; }
        public string COMPLAIN_DOCSERIES { get; set; }
        public Nullable<int> COMPLAIN_ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string USER_ROLE_CODE { get; set; }
        public string USER_ROLE_NAME { get; set; }
        public Nullable<int> USER_ROLE_ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> COMPLAIN_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> DRAFT_NUM { get; set; }
        public Nullable<int> DOC_NUM { get; set; }
        public string DOC_SERIES_CODE { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string DOC_STATUS { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
    }
}
