//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_product_master
    {
        public int ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DESC { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string PRODUCT_CATEGORY_CODE { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public string SIZE { get; set; }
        public Nullable<decimal> GROSS_WEIGHT { get; set; }
        public Nullable<decimal> NET_WEIGHT { get; set; }
        public string BASE_UNIT { get; set; }
        public Nullable<int> DEVIATION { get; set; }
        public string WEIGHT_UNIT { get; set; }
        public string DIVISION { get; set; }
        public string EXT_MATGRP { get; set; }
        public string MAT_DESC { get; set; }
        public string INDUSTRY_SECTOR { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public string VOLUME_UNIT { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string COLOR { get; set; }
        public string SIZE2 { get; set; }
        public Nullable<System.DateTime> SAP_CREATED_DATE { get; set; }
        public string SAP_CREATED_BY { get; set; }
        public Nullable<System.DateTime> SAP_MODIFIED_DATE { get; set; }
        public string CHAPTER_ID { get; set; }
        public string CHAPTER_DESC { get; set; }
        public string HSN_NO { get; set; }
    }
}
