//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_corrective_observations_lines
    {
        public int LINE_ID { get; set; }
        public int ID { get; set; }
        public string OBSERVATION_CODE { get; set; }
        public string OBSERVATION_NAME { get; set; }
    
        public virtual cms_corrective_measures cms_corrective_measures { get; set; }
        public virtual cms_corrective_measures cms_corrective_measures1 { get; set; }
    }
}
