//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_plant_master
    {
        public int ID { get; set; }
        public string PLANT_CODE { get; set; }
        public string PLANT_NAME { get; set; }
        public string PLANT_DESCRIPTION { get; set; }
        public string AREA_CODE { get; set; }
        public string ADDRESS { get; set; }
        public string ROOM_FLOOR { get; set; }
        public string BLOCK_BUILDING { get; set; }
        public string STREET_PO_BOX { get; set; }
        public string ZIP_CODE { get; set; }
        public string WEBSITE { get; set; }
        public string EMAIL { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string MOBILE { get; set; }
        public string FAX { get; set; }
        public string STATE_CODE { get; set; }
        public string CITY_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public string ZONE_CODE { get; set; }
        public string SALES_ORG_CODE { get; set; }
        public string DISTRIBUTION_CHANNEL_CODE { get; set; }
        public string INT_CO_BILLING_DIV { get; set; }
        public string DISTRICT { get; set; }
        public string STREET { get; set; }
        public string STREET2 { get; set; }
        public string STREET3 { get; set; }
        public string STREET4 { get; set; }
        public string STREET5 { get; set; }
        public string ECC_NO { get; set; }
        public string EXCISE_RANGE { get; set; }
        public string EXCISE_DIVISION { get; set; }
        public string EXCISE_COMMISIONARATE { get; set; }
        public string CST_NO { get; set; }
        public string TIN_NO { get; set; }
        public string PAN_NO { get; set; }
        public string BUSINESS_UNIT { get; set; }
        public string NAME3 { get; set; }
        public string GSTIN_NO { get; set; }
        public Nullable<int> GDashboard { get; set; }
        public string STOCK_TRANSFER { get; set; }
    }
}
