//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_investigation_site_observations_sheet_lines
    {
        public int LINE_ID { get; set; }
        public string OBSERVATION { get; set; }
        public string VARIFIED_OR_NOT { get; set; }
        public string COMMENTS { get; set; }
        public int ID { get; set; }
    }
}
