//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_userrole_producttype_lines
    {
        public int LINE_ID { get; set; }
        public Nullable<int> PRODUCT_TYPE_ID { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public string PRODUCT_TYPE_NAME { get; set; }
        public int ID { get; set; }
        public string PRODUCT_CATEGORY_CODE { get; set; }
        public string PRODUCT_CATEGORY_NAME { get; set; }
        public Nullable<int> PRODUCT_CATEGORY_ID { get; set; }
    
        public virtual cms_user_role_master cms_user_role_master { get; set; }
    }
}
