//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_register_complaints_sto
    {
        public cms_register_complaints_sto()
        {
            this.CMS_RC_Material_Supply_Details_STO = new HashSet<CMS_RC_Material_Supply_Details_STO>();
            this.CMS_RC_Supply_Details_STO = new HashSet<CMS_RC_Supply_Details_STO>();
        }
    
        public int ID { get; set; }
        public string COMPLAINT_CODE { get; set; }
        public string FROM_PLANT_CODE { get; set; }
        public Nullable<System.DateTime> COMPLAINT_RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> COMPLAINT_REGISTRATION_DATE { get; set; }
        public string COMPLAINT_TRACKING_NO { get; set; }
        public string REGISTRANT_TYPE_CODE { get; set; }
        public string DOC_SERIES_CODE { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public string PLANT_MHD_CODE { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public string COMPLAINT_DESC { get; set; }
        public string REMARKS { get; set; }
        public string ATTACHMENTS { get; set; }
        public string TO_PLANT_CODE { get; set; }
        public string END_CUSTOMER_DETAILS { get; set; }
        public string SITE_ADDRESS { get; set; }
        public string COMPLAINT_MODE_CODE { get; set; }
        public string PRODUCT_CATEGORY_CODE { get; set; }
        public string COMPLAINT_TYPE_CODE { get; set; }
        public string COMPLAINT_PRIORITY_CODE { get; set; }
        public string COMPLAINT_CATEGORY_CODE { get; set; }
        public string COMPLAINT_SEVERITY_CODE { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string NATURE_OF_COMPLAINT { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> DOC_NUM { get; set; }
        public Nullable<int> DRAFT_NUM { get; set; }
        public string DOC_STATUS { get; set; }
        public string APPROVED_BY { get; set; }
        public string CANCEL_BY { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string CANCEL_REMARKS { get; set; }
        public Nullable<bool> set_visible_draft_status { get; set; }
    
        public virtual ICollection<CMS_RC_Material_Supply_Details_STO> CMS_RC_Material_Supply_Details_STO { get; set; }
        public virtual ICollection<CMS_RC_Supply_Details_STO> CMS_RC_Supply_Details_STO { get; set; }
    }
}
