//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_COMPLAINT_STATUS_TRACKING
    {
        public int id { get; set; }
        public string COMPLAINT_TRACKING_NO { get; set; }
        public string COMPLAINT_STATUS { get; set; }
        public Nullable<System.DateTime> ORIGINATED_ON { get; set; }
        public string ORIGINATED_BY { get; set; }
    }
}
