//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_documentseries
    {
        public int ID { get; set; }
        public string DOCUMENT_CODE { get; set; }
        public Nullable<double> FIRST_NO { get; set; }
        public string SERIES_PREFIX { get; set; }
        public Nullable<double> LAST_NO { get; set; }
        public Nullable<double> NEXT_NO { get; set; }
        public string SERIES_SUFFIX { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string DOC_LOCK { get; set; }
        public string FINANCIAL_PERIOD { get; set; }
        public string DOCUMENT_SERIES_CODE { get; set; }
        public string DEFAULT_SERIES { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public int DOCUMENT_ID { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
    
        public virtual cms_documentmaster cms_documentmaster { get; set; }
        public virtual cms_documentmaster cms_documentmaster1 { get; set; }
    }
}
