//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_DASHBOARD_TABLE
    {
        public int id { get; set; }
        public string COMPLAINT_STATUS { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLE_ALIAS { get; set; }
        public string INNER_JOIN { get; set; }
        public string INNER_JOIN_ALIAS { get; set; }
        public string DATE_TYPE { get; set; }
        public string COLUMN_HEADER { get; set; }
        public string MSSQL_QUERY { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
