//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_investigation_invoice_lines
    {
        public int LINE_ID { get; set; }
        public int ID { get; set; }
        public Nullable<int> LINE_NUM { get; set; }
        public string INVOICE_NO { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public string REMARKS { get; set; }
    }
}
