//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_thickness_for_cc_sheet
    {
        public int Id { get; set; }
        public int COLOUR_ID { get; set; }
        public string THICKNESS { get; set; }
    }
}
