//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_compensation_recommlines_BU3
    {
        public int LINE_ID { get; set; }
        public int ID { get; set; }
        public string ProdCode { get; set; }
        public string ProdName { get; set; }
        public Nullable<int> Nos { get; set; }
    }
}
