//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_menu_view
    {
        public int IDD { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> LEVEL1 { get; set; }
        public string MENU_NAME { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string APPLICATION_CODE { get; set; }
        public string OBJECT_ID { get; set; }
        public string OBJECT { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
    }
}
