//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_compensation_CCSheets
    {
        public int ID { get; set; }
        public int HeaderId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Nos { get; set; }
        public string GrossWeight { get; set; }
        public string Tons { get; set; }
    }
}
