//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_log_string
    {
        public string DOC_CODE { get; set; }
        public System.DateTime TIMESTAMPP { get; set; }
        public string DOC_STRING { get; set; }
        public int ID { get; set; }
        public string OPERATION_NAME { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public string SITEDETAIL_CODE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string TABLE_NAME { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
