//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_corrective_measures
    {
        public cms_corrective_measures()
        {
            this.cms_corrective_chosen_permanent_lines = new HashSet<cms_corrective_chosen_permanent_lines>();
            this.cms_corrective_emergency_response_lines = new HashSet<cms_corrective_emergency_response_lines>();
            this.cms_corrective_implement_permanent_lines = new HashSet<cms_corrective_implement_permanent_lines>();
            this.cms_corrective_interim_containment_lines = new HashSet<cms_corrective_interim_containment_lines>();
            this.cms_corrective_root_causes_escape_lines = new HashSet<cms_corrective_root_causes_escape_lines>();
            this.cms_corrective_team_involved_lines = new HashSet<cms_corrective_team_involved_lines>();
            this.cms_corrective_observations_lines = new HashSet<cms_corrective_observations_lines>();
            this.cms_corrective_observations_lines1 = new HashSet<cms_corrective_observations_lines>();
            this.cms_corrective_verification_lines = new HashSet<cms_corrective_verification_lines>();
            this.cms_corrective_measures_msf = new HashSet<cms_corrective_measures_msf>();
            this.cms_preventive_lines = new HashSet<cms_preventive_lines>();
            this.cms_preventive_verification_lines = new HashSet<cms_preventive_verification_lines>();
        }
    
        public int ID { get; set; }
        public System.DateTime COMPLAINT_RECEIVED_DATE { get; set; }
        public Nullable<System.DateTime> VISITED_DATE { get; set; }
        public string REMARKS { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string CUSTOMER_REMARKS { get; set; }
        public string Complaint_Category { get; set; }
        public string Complaint_Type { get; set; }
        public string Symptoms { get; set; }
        public string Complaint_Impact { get; set; }
        public string Problem_Description { get; set; }
        public string Observations_by_Investigator { get; set; }
        public string Notice_Issued { get; set; }
        public string Notice_Issue_No { get; set; }
        public Nullable<System.DateTime> Notice_Issue_Date { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> INVESTIGATION_DATE { get; set; }
        public string COMPANYDETAIL_CODE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> DRAFT_NUM { get; set; }
        public Nullable<int> DOC_NUM { get; set; }
        public string DOC_SERIES_CODE { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string DOC_STATUS { get; set; }
        public Nullable<System.DateTime> APPROVED_DATE { get; set; }
        public Nullable<int> INVESTIGATION_ID { get; set; }
        public string INVESTIGATION_DOC_SERIES { get; set; }
        public Nullable<int> INVESTIGATION_DOC_NUM { get; set; }
        public string Complaint_Desc { get; set; }
        public string Product_Category_Code { get; set; }
        public string Product_Code { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_type_Code { get; set; }
        public string PLANT_CODE { get; set; }
        public string DEPO_CODE { get; set; }
        public string PRODUCT_TYPE_CODE { get; set; }
        public string CITY_CODE { get; set; }
        public string COMPLAINT_CODE { get; set; }
        public string COMPLAINT_DOC_SERIES { get; set; }
        public Nullable<int> COMPLAINT_DOC_NUM { get; set; }
        public string CANCEL_REMARKS { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public string CANCEL_BY { get; set; }
        public string LOCATION { get; set; }
        public string Invoice_No { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public string Defect { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<int> NO_OF_DEFICTIVE_SHEETS { get; set; }
        public string NOTICE_REMARKS { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string CM_STATUS { get; set; }
        public string APPROVED_BY { get; set; }
        public string InvestigatorCode { get; set; }
        public string Conclusion { get; set; }
    
        public virtual ICollection<cms_corrective_chosen_permanent_lines> cms_corrective_chosen_permanent_lines { get; set; }
        public virtual ICollection<cms_corrective_emergency_response_lines> cms_corrective_emergency_response_lines { get; set; }
        public virtual ICollection<cms_corrective_implement_permanent_lines> cms_corrective_implement_permanent_lines { get; set; }
        public virtual ICollection<cms_corrective_interim_containment_lines> cms_corrective_interim_containment_lines { get; set; }
        public virtual ICollection<cms_corrective_root_causes_escape_lines> cms_corrective_root_causes_escape_lines { get; set; }
        public virtual ICollection<cms_corrective_team_involved_lines> cms_corrective_team_involved_lines { get; set; }
        public virtual ICollection<cms_corrective_observations_lines> cms_corrective_observations_lines { get; set; }
        public virtual ICollection<cms_corrective_observations_lines> cms_corrective_observations_lines1 { get; set; }
        public virtual ICollection<cms_corrective_verification_lines> cms_corrective_verification_lines { get; set; }
        public virtual ICollection<cms_corrective_measures_msf> cms_corrective_measures_msf { get; set; }
        public virtual ICollection<cms_preventive_lines> cms_preventive_lines { get; set; }
        public virtual ICollection<cms_preventive_verification_lines> cms_preventive_verification_lines { get; set; }
    }
}
