//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLUMN_MAPPING
    {
        public int ID { get; set; }
        public string REPORT_NAME { get; set; }
        public string TABLE_NAME { get; set; }
        public string FRONT_END_COLUMN_NAME { get; set; }
        public string DB_END_COLUMN_NAME { get; set; }
    }
}
