//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimsUser
    {
        public DimsUser()
        {
            this.SAP_INVOICE_LIST = new HashSet<SAP_INVOICE_LIST>();
            this.SAP_PAYMENT_BY_STOCKIST = new HashSet<SAP_PAYMENT_BY_STOCKIST>();
            this.SAP_PENDING_C_FORM = new HashSet<SAP_PENDING_C_FORM>();
        }
    
        public int ID { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public string TOKEN { get; set; }
        public string PWDCHNGSTATUS { get; set; }
        public Nullable<System.DateTime> LASTPWDCHNGDATE { get; set; }
        public Nullable<int> USER_ROLE_ID { get; set; }
        public string USER_ROLE_CODE { get; set; }
        public string USER_ROLE_NAME { get; set; }
        public string SITE_DETAIL_CODE { get; set; }
        public string COMPANY_DETAIL_CODE { get; set; }
        public string LAST_ACTION { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public string USER_TYPE { get; set; }
        public string USER_AUTHENTICATION_IMAGE { get; set; }
        public string PASS_ORG { get; set; }
    
        public virtual ICollection<SAP_INVOICE_LIST> SAP_INVOICE_LIST { get; set; }
        public virtual ICollection<SAP_PAYMENT_BY_STOCKIST> SAP_PAYMENT_BY_STOCKIST { get; set; }
        public virtual ICollection<SAP_PENDING_C_FORM> SAP_PENDING_C_FORM { get; set; }
    }
}
