//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIMS_MEMBERSHIPID_CUSTOMER_CONFIGURATION
    {
        public int ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public Nullable<int> ORG_LEVEL_ID { get; set; }
    }
}
