//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIMS_SFDC_PARTNER_ISSUE
    {
        public int ID { get; set; }
        public int PARTNER_ISSUE_NUMBER { get; set; }
        public string ISSUE_CREATED_BY { get; set; }
        public System.DateTime ISSUE_CREATED_DATE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string ISSUE_VERIFIED { get; set; }
        public string ISSUE_STATUS { get; set; }
        public string FIRST_PERSON_RESPONSIBLE { get; set; }
        public Nullable<System.DateTime> ISSUE_COMMITED_CLOSER_DATE { get; set; }
        public string ISSUE_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> ACTUAL_CLOSED_DATE { get; set; }
        public string REMARK { get; set; }
        public string ZONE_CODE { get; set; }
        public string STATE_CODE { get; set; }
        public string TERRITORY { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
