//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIMS_PARTNER_ISSUE_HISTORYs
    {
        public int ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public string Comment { get; set; }
        public int PartnerIssueNumber { get; set; }
    }
}
