//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_Structures
    {
        public Discount_Structures()
        {
            this.Discount_Structure_Status = new HashSet<Discount_Structure_Status>();
        }
    
        public int Id { get; set; }
        public string Discount_Id { get; set; }
        public string CreatedBy { get; set; }
        public string Discount_Category { get; set; }
        public string State_Location_Based { get; set; }
        public string Sales_Group_Code { get; set; }
        public string Sales_Group_Desc { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Zone { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Discount_Type { get; set; }
        public System.DateTime Discount_Valid_From { get; set; }
        public System.DateTime Discount_Valid_To { get; set; }
        public double Discount_Applicable_Running_Meter { get; set; }
        public Nullable<double> Expected_Sale { get; set; }
        public Nullable<double> Target { get; set; }
        public double Total_Discount { get; set; }
        public double Price_card_Rate { get; set; }
        public double Net_Landing_Price { get; set; }
        public Nullable<double> Expected_Nsr { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ZH_Status_Changed_Date { get; set; }
        public string ZH_Status { get; set; }
        public Nullable<System.DateTime> NSH_Status_Changed_Date { get; set; }
        public string NSH_Status { get; set; }
        public string Created_Name { get; set; }
        public Nullable<double> KSM { get; set; }
        public Nullable<double> CD { get; set; }
        public Nullable<double> Other { get; set; }
    
        public virtual ICollection<Discount_Structure_Status> Discount_Structure_Status { get; set; }
    }
}
