//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GET_CSO_ROLES
    {
        public int ID { get; set; }
        public string ORG_LEVEL_NAME { get; set; }
        public string STATE_CODE { get; set; }
        public string REPORTING_TO { get; set; }
        public string EMPLOYEE_CODDE { get; set; }
    }
}
