//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIL_ZONAL_COORDINATORS
    {
        public int ID { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string STATE_NAME { get; set; }
        public string ZONE_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
