//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pricing_Card_Rates
    {
        public string Sales_Group_Code { get; set; }
        public string Sales_Group_Name { get; set; }
        public double Price_Card_Rate { get; set; }
        public System.DateTime Created_Date { get; set; }
    }
}
