//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReturnEmail
    {
        public int ID { get; set; }
        public string Emails { get; set; }
        public string ProductTypeCode { get; set; }
        public Nullable<int> status { get; set; }
        public string UserName { get; set; }
    }
}
