//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sap_invoice_header_data
    {
        public int ID { get; set; }
        public string DOC_NO { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<System.TimeSpan> TIME { get; set; }
        public Nullable<decimal> INV_VALUE { get; set; }
        public string DISCH_CHANNEL { get; set; }
        public string STK_PRC_GRP { get; set; }
        public string DIVISION { get; set; }
        public string STK_GRP { get; set; }
        public string DELIVERY { get; set; }
        public string PAYMENT_TERMS { get; set; }
        public string VEHICLE_NO { get; set; }
        public string LR_NO { get; set; }
        public string DRIVER_NO { get; set; }
        public Nullable<decimal> EXCISE_INV { get; set; }
        public Nullable<System.DateTime> EXCISE_INV_DATE { get; set; }
        public string BILL_TO_PARTY_CODE { get; set; }
        public string BILL_TO_PARTY_NO { get; set; }
        public string SHIP_TO_PARTY_CODE { get; set; }
        public string SHIP_TO_PARTY_NO { get; set; }
        public string AGENT_CODE { get; set; }
        public string AGENT_NAME { get; set; }
        public string SALES_EMPLOYEE { get; set; }
        public string TRANSPORTER_CODE { get; set; }
        public string TRANSPORTER { get; set; }
        public string ECC_NUMBER { get; set; }
        public string EXCISE_RANGE { get; set; }
        public string EXCISE_DIVISION { get; set; }
        public string EXCISE_COMMISIONARATE { get; set; }
        public string SALES_ORDER { get; set; }
        public Nullable<System.DateTime> SALES_ORDER_DATE { get; set; }
        public string DELIVERY_NO { get; set; }
        public string REFERENCE_ORDER { get; set; }
        public Nullable<System.DateTime> REFERENCE_DATE { get; set; }
        public string SOLD_TO_PART { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string SOLD_TO_PARTY_CODE { get; set; }
        public string SOLD_TO_PARTY_NO { get; set; }
        public string PAYER_CODE { get; set; }
        public string PAYER_NO { get; set; }
        public string INV_TYPE { get; set; }
        public Nullable<System.DateTime> SAP_MODIFIED_DATE { get; set; }
        public Nullable<decimal> GAMOUNT { get; set; }
        public Nullable<decimal> DISC { get; set; }
        public Nullable<decimal> ASS { get; set; }
        public Nullable<decimal> ZVAT { get; set; }
        public Nullable<decimal> JCST { get; set; }
        public Nullable<decimal> JEXP { get; set; }
        public Nullable<decimal> ZETX { get; set; }
        public Nullable<decimal> ZSSC { get; set; }
        public Nullable<decimal> ZETO { get; set; }
        public Nullable<decimal> ZGTA { get; set; }
        public Nullable<decimal> ZINS { get; set; }
        public Nullable<decimal> ZF00 { get; set; }
        public string TRANSPORTER_NAME { get; set; }
        public Nullable<decimal> ZBPS { get; set; }
        public Nullable<decimal> ZTCS { get; set; }
        public Nullable<decimal> JCSTP { get; set; }
        public Nullable<decimal> JEXCPP { get; set; }
        public Nullable<decimal> ZASSP { get; set; }
        public Nullable<decimal> ZETOP { get; set; }
        public Nullable<decimal> ZETXP { get; set; }
        public Nullable<decimal> ZGTAP { get; set; }
        public Nullable<decimal> ZINSP { get; set; }
        public Nullable<decimal> ZOD1P { get; set; }
        public Nullable<decimal> ZOD2P { get; set; }
        public Nullable<decimal> ZSSCP { get; set; }
        public Nullable<decimal> ZVATP { get; set; }
        public Nullable<decimal> GST_GAMT { get; set; }
        public string ZZEWAY_BILLNO { get; set; }
        public string INS_POLICY_NO { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> IGSTP { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> CGSTP { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> SGSTP { get; set; }
        public Nullable<decimal> JTCB { get; set; }
        public Nullable<decimal> JTC1 { get; set; }
        public Nullable<decimal> JTC1P { get; set; }
    }
}
