//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_SALES_OFFICE
    {
        public int ID { get; set; }
        public string SALES_OFFICE_CODE { get; set; }
        public string SALES_OFFICE_DESC { get; set; }
        public string ADDRESS { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string STREET_HOUSE { get; set; }
        public string POST_CODE1 { get; set; }
        public string POST_CODE2 { get; set; }
        public string PO_BOX { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string REGION { get; set; }
        public string TIME_ZONE { get; set; }
        public string LANGUAGE_KEY { get; set; }
        public string TELEPHONE1 { get; set; }
        public string TELEPHONE2 { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
