//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sap_customer_master
    {
        public string STOCKIST_ID { get; set; }
        public string STOCKIST_NAME { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string CUSTOMER_DISTRICT { get; set; }
        public string POSTAL_CODE { get; set; }
        public string STREET { get; set; }
        public string STATE { get; set; }
        public string CREATED_BY { get; set; }
        public string SAP_CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> SAP_CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CONTACT_PERSON1_NAME { get; set; }
        public string CONTACT_PERSON2_NAME { get; set; }
        public string TIN_NO { get; set; }
        public string PAN_NO { get; set; }
        public string VAT_NO { get; set; }
        public string ACCOUNT_GROUP_CODE { get; set; }
        public string EMAIL { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string FAX { get; set; }
        public string LAST_ACTION { get; set; }
        public string ACTIVE { get; set; }
        public string STREET2 { get; set; }
        public string STREET3 { get; set; }
        public string STREET4 { get; set; }
        public string STREET5 { get; set; }
        public string POSTAL_CODE2 { get; set; }
        public string PO_BOX { get; set; }
        public string TIME_ZONE { get; set; }
        public string LANGUAGE_KEY { get; set; }
        public string CST_NO { get; set; }
        public string TRANSP_ZONE { get; set; }
        public string GST_NO { get; set; }
    }
}
