//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sap_customer_sales_master
    {
        public int ID { get; set; }
        public string STOCKIST_ID { get; set; }
        public string SALES_ORGANISATION { get; set; }
        public string DISTRIBUTION_CHANNEL { get; set; }
        public string DIVISION { get; set; }
        public string STOCKIST_GROUP { get; set; }
        public string TERRITORY_AREA { get; set; }
        public string STOCKIST_PRICING_GROUP { get; set; }
        public string SALES_GROUP { get; set; }
        public string ZONE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string SALES_DISTRICT { get; set; }
        public string STOCKIST_PRICING_PROCEDURE { get; set; }
        public string AUFSD { get; set; }
        public string LIFSD { get; set; }
        public string FAKSD { get; set; }
    }
}
