//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sap_credit_debit_note
    {
        public int ID { get; set; }
        public string COMPANY_CODE { get; set; }
        public string DOC_NO { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string ASSIGNMENT { get; set; }
        public string TEXT { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string INVOICE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public int YEAR { get; set; }
        public string SALES_EMPLOYEE { get; set; }
        public string ITEM_NO { get; set; }
        public Nullable<System.DateTime> POSTING_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<System.TimeSpan> ENTRY_TIME { get; set; }
        public string REV_DOC { get; set; }
        public Nullable<System.DateTime> CLEARING_DATE { get; set; }
        public string POSTING_KEY { get; set; }
        public string BUSINESS_AREA { get; set; }
        public Nullable<System.DateTime> DOC_CHANGE { get; set; }
        public Nullable<System.DateTime> DOC_UPDATE { get; set; }
        public string INDICATOR { get; set; }
        public string SPL_GL { get; set; }
        public Nullable<decimal> WT_TAX_AMT { get; set; }
        public Nullable<decimal> BASE_AMT { get; set; }
        public string CGST { get; set; }
        public Nullable<decimal> CGST_P { get; set; }
        public string SGST { get; set; }
        public Nullable<decimal> SGST_P { get; set; }
        public string IGST { get; set; }
        public Nullable<decimal> IGST_P { get; set; }
        public string REF_DOC { get; set; }
        public string REF_DATE { get; set; }
        public string MAT_CODE { get; set; }
        public string MAT_TXT { get; set; }
        public Nullable<decimal> QNTY { get; set; }
        public string UNIT { get; set; }
        public string HSN_CODE { get; set; }
        public Nullable<decimal> UNIT_RATE { get; set; }
        public string REMARKS { get; set; }
    }
}
