//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_SALES_AND_DISTRIBUTION
    {
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string STOCKIST_ID { get; set; }
        public string STOCKIST_NAME { get; set; }
        public string STOCKIST_ADDRESS { get; set; }
        public string SALES_EMPLOYEE { get; set; }
        public string ZONE { get; set; }
        public string STATE { get; set; }
        public string TERRITORY { get; set; }
        public string LOCATION { get; set; }
        public decimal OUTSTANDING { get; set; }
        public string NARRATION { get; set; }
        public System.DateTime POSTING_DATE { get; set; }
        public string DOCUMENT_NUMBER { get; set; }
        public string ASSIGNMENT { get; set; }
        public string TEXT { get; set; }
        public decimal CREDIT_DEBIT_AMOUNT { get; set; }
        public string BILLING_DOC_NO { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public decimal TOTAL_INVOICE_VALUE { get; set; }
        public string STOCKIST_PRICING_GROUP { get; set; }
        public string SALES_GROUP { get; set; }
        public string PLANT_CODE { get; set; }
        public string PLANT_DESC { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string MATERIAL_DESC { get; set; }
        public decimal BILL_QTY { get; set; }
        public string UOM { get; set; }
        public decimal GROSS_WEIGHT_MT { get; set; }
        public string DIVISION { get; set; }
        public string STOCKIST_GROUP { get; set; }
        public string BILL_TO_PARTY_CODE { get; set; }
        public string BILL_TO_PARTY_NAME { get; set; }
        public string SHIP_TO_PARTY_CODE { get; set; }
        public string SHIP_TO_PARTY_NAME { get; set; }
        public string AGENT_CODE { get; set; }
        public string AGENT_NAME { get; set; }
        public string EXCISE_INV_NO { get; set; }
        public string TRANSPORTER_CODE { get; set; }
        public string TRANSPORTER_NAME { get; set; }
        public string VEHICLE_NO { get; set; }
        public string DRIVER_MOB_NO { get; set; }
        public System.DateTime MATERIAL_RECEIPT_DATE { get; set; }
        public string STOCKIST_REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
