//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_DAILY_ORDERs
    {
        public SFDC_DAILY_ORDERs()
        {
            this.SFDC_DAILY_ORDER_PRODUCT_DETAILS = new HashSet<SFDC_DAILY_ORDER_PRODUCT_DETAILS>();
        }
    
        public int ID { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public string SALES_EMPLOYEE { get; set; }
        public string DIMS_ORDER_ID { get; set; }
        public string ORDER_NUMBER { get; set; }
        public System.DateTime ORDER_CREATED_DATE { get; set; }
        public System.DateTime ORDER_DELIVERY_DATE { get; set; }
        public string DELIVERY_SOURCE { get; set; }
        public string SALES_CO_ORDINATOR { get; set; }
        public string SOURCE_ZONE { get; set; }
        public string SOURCE_LOCATION { get; set; }
        public string STOCKIST_NAME { get; set; }
        public string STOCKIST_CODE { get; set; }
        public string ZONE { get; set; }
        public string STATE { get; set; }
        public string TERRITORY_AREA { get; set; }
        public string LOCATION { get; set; }
        public string PIN_CODE { get; set; }
        public string RETAILER_NAME { get; set; }
        public string RETAILER_CODE { get; set; }
        public string BILLING_ADDRESS { get; set; }
        public string SHIP_TO { get; set; }
        public string CREDIT_LIMIT { get; set; }
        public decimal OUTSTANDING_AMOUNT { get; set; }
        public string DELIVERY_TYPE { get; set; }
        public Nullable<bool> PROJECT_CUSTOMER { get; set; }
        public Nullable<bool> CFROM_REQUIRED { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<SFDC_DAILY_ORDER_PRODUCT_DETAILS> SFDC_DAILY_ORDER_PRODUCT_DETAILS { get; set; }
    }
}
