//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_ADV_JOURNEY_PLAN_CUSTOMER_DETAILs
    {
        public int ID { get; set; }
        public int HEADER_ID { get; set; }
        public string SALES_EMPLOYEE_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_TYPE { get; set; }
        public string COUNTER_EXISTANCE { get; set; }
        public string SALES_DISTRICT { get; set; }
        public string SALES_REGION { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string PLAN_FOR_MONTH { get; set; }
        public Nullable<decimal> LAST_YEAR_SAME_MONTH_AVG { get; set; }
        public Nullable<double> ACTUAL_VOLUME_MTD { get; set; }
        public int NO_OF_DAYS_IN_MONTH { get; set; }
        public Nullable<System.DateTime> LAST_ORDER_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_ORDER_DATE { get; set; }
        public Nullable<decimal> LAST_QUARTER_MONTH_AVG { get; set; }
        public decimal VOLUME_PLAN_FOR_MONTH { get; set; }
    }
}
