//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_ADD_COUNTERs
    {
        public int ID { get; set; }
        public string CREATE_ORDER_REF_ID { get; set; }
        public string SALES_EMPLOYEE_NAME { get; set; }
        public string SALES_REGION { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_TYPE_NAME { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string STOCKIST_CODE { get; set; }
        public double EXCEPTED_VOLUME_TARGET { get; set; }
        public string PINCODE { get; set; }
        public string CONTACT_PERSON_NAME { get; set; }
        public string CUSTOMER_STATE { get; set; }
        public string CUSTOMER_PHONE_NUMBER { get; set; }
        public string CUSTOMER_CITY { get; set; }
        public string CUSTOMER_EMAIL_ID { get; set; }
        public string CUSTOMER_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
