//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_SALES_HUDDLES
    {
        public int ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string STATEHEAD_CODE { get; set; }
        public string EMPLOYEE_ROLE_CODE { get; set; }
        public string STATECODE { get; set; }
        public string ZONECODE { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string DAY1 { get; set; }
        public string DAY2 { get; set; }
        public string DAY3 { get; set; }
        public string DAY4 { get; set; }
        public string DAY5 { get; set; }
        public string DAY6 { get; set; }
        public string DAY7 { get; set; }
        public string DAY8 { get; set; }
        public string DAY9 { get; set; }
        public string DAY10 { get; set; }
        public string DAY11 { get; set; }
        public string DAY12 { get; set; }
        public string DAY13 { get; set; }
        public string DAY14 { get; set; }
        public string DAY15 { get; set; }
        public string DAY16 { get; set; }
        public string DAY17 { get; set; }
        public string DAY18 { get; set; }
        public string DAY19 { get; set; }
        public string DAY20 { get; set; }
        public string DAY21 { get; set; }
        public string DAY22 { get; set; }
        public string DAY23 { get; set; }
        public string DAY24 { get; set; }
        public string DAY25 { get; set; }
        public string DAY26 { get; set; }
        public string DAY27 { get; set; }
        public string DAY28 { get; set; }
        public string DAY29 { get; set; }
        public string DAY30 { get; set; }
        public string DAY31 { get; set; }
    }
}
