//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_INVENTORY_TRACK_DETAILS_COMPANY
    {
        public int ID { get; set; }
        public int HEADER_ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<double> SKU_SIZE3_60 { get; set; }
        public Nullable<double> SKU_SIZE_3_00 { get; set; }
        public Nullable<double> SKU_SIZE_2_75 { get; set; }
        public Nullable<double> SKU_SIZE_2_50 { get; set; }
        public Nullable<double> SKU_SIZE_2_25 { get; set; }
        public Nullable<double> SKU_SIZE_2_00 { get; set; }
        public Nullable<double> SKU_SIZE_1_75 { get; set; }
        public Nullable<double> SKU_SIZE_1_50 { get; set; }
        public Nullable<double> SKU_SIZE_1_25 { get; set; }
        public Nullable<double> SKU_SIZE_1_00 { get; set; }
        public Nullable<double> TOTAL_IN_RUN_METER { get; set; }
        public Nullable<double> TOTAL_IN_MT { get; set; }
        public string REMARKS { get; set; }
    
        public virtual SFDC_INVENTORY_TRACK_DETAILs SFDC_INVENTORY_TRACK_DETAILs { get; set; }
        public virtual SFDC_INVENTORY_TRACK_DETAILs SFDC_INVENTORY_TRACK_DETAILs1 { get; set; }
    }
}
