//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_SALES_HUDDLES_POPUP_DATAs
    {
        public int ID { get; set; }
        public string DAILY { get; set; }
        public string WEEKLY { get; set; }
        public string WEEKLY_TIME { get; set; }
        public string MONTHLY { get; set; }
    }
}
