//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_Save_COUNTER_DETAILs
    {
        public int ID { get; set; }
        public string SALES_EMPLOYEE_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_TYPE { get; set; }
        public string CUSTOMER_PAN_NUMBER { get; set; }
        public string CUSTOMER_TIN_NUMBER { get; set; }
        public Nullable<double> EXPECTED_VOLUME_TARGET { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string CONTACT_PERSON_NAME { get; set; }
        public string CONTACT_PERSON_NUMBER { get; set; }
        public string CUSTOMER_PIN_CODE { get; set; }
        public string CUSTOMER_EMAIL_ID { get; set; }
        public string CUSTOMER_STATE { get; set; }
        public string CUSTOMER_CITY { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CUSTOMER_DISTRICT { get; set; }
        public string SAP_CODE { get; set; }
        public Nullable<int> ORG_LEVEL_ID { get; set; }
        public string JP_COUNTERDETAILS_ID { get; set; }
        public string SAP_CUSTOMER_TYPE { get; set; }
        public string AUTO_ID { get; set; }
    }
}
