//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_CreateTargets
    {
        public SFDC_CreateTargets()
        {
            this.SFDC_CreateTargets_Lines = new HashSet<SFDC_CreateTargets_Lines>();
            this.SFDC_CreateTargets_Lines1 = new HashSet<SFDC_CreateTargets_Lines>();
        }
    
        public int ID { get; set; }
        public string Zone { get; set; }
        public string StateCode { get; set; }
        public string StateHeadEmpCode { get; set; }
        public string StateTarget { get; set; }
        public string MonthYear { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> RevenueTarget { get; set; }
        public Nullable<decimal> SHCreditTarget { get; set; }
        public Nullable<decimal> SHCreditApprovals { get; set; }
        public Nullable<decimal> TMCreditTarget { get; set; }
        public Nullable<decimal> TMCreditApprovals { get; set; }
    
        public virtual ICollection<SFDC_CreateTargets_Lines> SFDC_CreateTargets_Lines { get; set; }
        public virtual ICollection<SFDC_CreateTargets_Lines> SFDC_CreateTargets_Lines1 { get; set; }
    }
}
