//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_SALES_HUDDLE_WEEKLYs
    {
        public int ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_CODE { get; set; }
        public string STATEHEAD_CODE { get; set; }
        public string EMPLOYEE_ROLE_CODE { get; set; }
        public string STATECODE { get; set; }
        public string ZONECODE { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string WEEK1 { get; set; }
        public string WEEK2 { get; set; }
        public string WEEK3 { get; set; }
        public string WEEK4 { get; set; }
        public string WEEK5 { get; set; }
    }
}
