//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_CONFIGURE_HOLIDAYS
    {
        public SFDC_CONFIGURE_HOLIDAYS()
        {
            this.SFDC_CONFIGURE_HOLIDAY_STATE = new HashSet<SFDC_CONFIGURE_HOLIDAY_STATE>();
            this.SFDC_CONFIGURE_HOLIDAY_STATE1 = new HashSet<SFDC_CONFIGURE_HOLIDAY_STATE>();
        }
    
        public int ID { get; set; }
        public string OCCASSION { get; set; }
        public System.DateTime OCCASSION_DATE { get; set; }
        public string OCCASSION_DAY { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<SFDC_CONFIGURE_HOLIDAY_STATE> SFDC_CONFIGURE_HOLIDAY_STATE { get; set; }
        public virtual ICollection<SFDC_CONFIGURE_HOLIDAY_STATE> SFDC_CONFIGURE_HOLIDAY_STATE1 { get; set; }
    }
}
