//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFDC_ID_GENERATIONs
    {
        public string DIMS_ORDER_NO { get; set; }
        public string DIMS_SCHEMES_ID { get; set; }
        public string DIMS_PARTNER_NO { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string REPORTS_DISCOUNT_ID { get; set; }
        public string REPORTS_NET_BILLING_ID { get; set; }
        public string PROJECT_DISCOUNT_WITH_COMMISSION_ID { get; set; }
        public string REPORTS_DISCOUNT_DIRECT_ID { get; set; }
    }
}
