//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_MODEM_SETTING
    {
        public int ID { get; set; }
        public string SerialPortName { get; set; }
        public int BitsPerSecond { get; set; }
        public int DataBits { get; set; }
        public string Parity { get; set; }
        public int StopBits { get; set; }
        public string DataBaseURL { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
