//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPM_ZH_JOURNEY_PLAN_DETAILS
    {
        public int ID { get; set; }
        public int HEADER_ID { get; set; }
        public string SALES_EMPLOYEE_CODE { get; set; }
        public string JOURNEY_PLAN_NAME { get; set; }
        public System.DateTime PLAN_DATE { get; set; }
        public string PLAN_DAY { get; set; }
        public string ATTENDANCE_TYPE { get; set; }
        public string PLANED_STATE { get; set; }
        public string PLANED_DISTRICT { get; set; }
        public string ACTUAL_VISIT_STATUS { get; set; }
        public string REMARKS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
