//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateWiseDiscount
    {
        public int Id { get; set; }
        public string STATE_CODE { get; set; }
        public string STATE_DESC { get; set; }
        public Nullable<decimal> Discount { get; set; }
    }
}
