//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNNATI_TRANSACTIONS
    {
        public int ID { get; set; }
        public string MEMBERSHIP_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string MEMEBER_TYPE { get; set; }
        public string AGENCY_NAME { get; set; }
        public string FSO_NAME { get; set; }
        public string TRANSACTION_ID { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public Nullable<System.DateTime> SOLD_DATE { get; set; }
        public Nullable<double> PURCHASE_AMOUNT { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string COMPAIGN_NAME { get; set; }
        public Nullable<double> POINTS { get; set; }
        public string INVOICE_NO { get; set; }
        public string STATUS { get; set; }
        public string FSO_CONTACT_NO { get; set; }
        public string TALUK { get; set; }
        public string VILLAGE { get; set; }
        public string ZONE { get; set; }
        public string DISTRICT { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<double> TOTAL_METERS { get; set; }
        public Nullable<System.DateTime> REWARD_POSTING_DATE { get; set; }
        public Nullable<System.DateTime> MEMBER_CLAIM_DATE { get; set; }
        public string STOCKIEST_ID { get; set; }
        public string PENDING_AT_USER { get; set; }
        public string TYPE_OF_TRANSACTION { get; set; }
    }
}
