//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNNATI_REDEMPTION
    {
        public int ID { get; set; }
        public string MEMBERSHIP_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string MEMEBER_TYPE { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<System.DateTime> STATUS_CHANGE_DATE { get; set; }
        public string ORDER_NO { get; set; }
        public string SUB_ORDER_NO { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> POINTS { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string NC_PRODUCT_CODE { get; set; }
        public string ZONE { get; set; }
        public string CONTACT_NO { get; set; }
        public string STATE { get; set; }
        public string CITY { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> PRODUCT_MRP_VALUE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string FSO_NAME { get; set; }
        public string AGENCY_NAME { get; set; }
    }
}
