//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNNATI_MAIL_CATEGORY
    {
        public int ID { get; set; }
        public string EMAIL_ID { get; set; }
        public string CATEGORY { get; set; }
        public string NAME { get; set; }
    }
}
