//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNNATI_MEMBER_ENROLLMENT
    {
        public int ID { get; set; }
        public string MEMBERSHIP_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string MEMBER_TYPE { get; set; }
        public string MEMBER_SALUTATION { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.DateTime> ENROLLEMENT_DATE { get; set; }
        public string ZONE { get; set; }
        public string DISTRICT { get; set; }
        public string STATE { get; set; }
        public string TALUK { get; set; }
        public string VILLAGE { get; set; }
        public string RESIDENTIAL_ADDRESS { get; set; }
        public string RESIDENTIAL_CITY { get; set; }
        public string RESIDENTIAL_STATE { get; set; }
        public string RESIDENTIAL_PINCODE { get; set; }
        public string CONTACT_NO { get; set; }
        public string EMAIL_ID { get; set; }
        public Nullable<double> POINT_BALANCE { get; set; }
        public Nullable<double> POINT_EARNED { get; set; }
        public Nullable<double> POINT_REDEEMED { get; set; }
        public Nullable<System.DateTime> MEMERSHIP_EXPIRY_DATE { get; set; }
        public string OFFICE_ADDRESS { get; set; }
        public string OFFICE_CITY { get; set; }
        public string OFFICE_PINCODE { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SPOUSE_SALUTATION { get; set; }
        public string SPOUSE_FIRST_NAME { get; set; }
        public string SPOUSE_LAST_NAME { get; set; }
        public Nullable<System.DateTime> SPOUSE_DOB { get; set; }
        public string CHILD_ONE_NAME { get; set; }
        public Nullable<System.DateTime> CHILD_ONE_DOB { get; set; }
        public string CHILD_TWO_NAME { get; set; }
        public Nullable<System.DateTime> CHILD_TWO_DOB { get; set; }
        public string CHILD_THREE_NAME { get; set; }
        public Nullable<System.DateTime> CHILD_THREE_DOB { get; set; }
        public Nullable<System.DateTime> ANNIVERSARY_DATE { get; set; }
        public string FIRM_NAME { get; set; }
        public string OTHER_MAJOR_MATERIAL_DEALT { get; set; }
        public string TYPE_OF_BUSINESS { get; set; }
        public string TIN_VAT_NO { get; set; }
        public string FSO_NAME { get; set; }
        public string FSO_CONTACT_NO { get; set; }
        public string FSO_EMAIL_ID { get; set; }
        public string STOCKIEST_FIRM_NAME { get; set; }
        public string STOCKIEST_MEMBERSHIP_ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
    }
}
